/*
 * File: app/store/ruleZQ.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.ruleZQ', {
    extend: 'Ext.data.Store',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'ruleZQ',
            data: [
                {
                    iniTime: '2013-3-3',
                    nameRule: '上传拆迁效果照片',
                    period: 3,
                    nextDate: '2013-1-1'
                },
                {
                    iniTime: '2013-3-2',
                    nameRule: '上传权利证明文件',
                    period: 2,
                    nextDate: '2013-1-3'
                }
            ],
            fields: [
                {
                    name: 'iniTime',
                    type: 'date'
                },
                {
                    name: 'nameRule',
                    type: 'string'
                },
                {
                    name: 'period',
                    type: 'int'
                },
                {
                    name: 'nextDate',
                    type: 'date'
                }
            ]
        }, cfg)]);
    }
});