/*
 * File: app/store/TaishiPriceCombox.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.TaishiPriceCombox', {
    extend: 'Ext.data.Store',
    alias: 'store.TaishiPriceCombox',

    requires: [
        'MyApp.model.TaishiPriceTextField'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            model: 'MyApp.model.TaishiPriceTextField',
            storeId: 'TaishiPriceCombox',
            data: [
                [
                    '凤城街道',
                    '1'
                ],
                [
                    '晏家街道',
                    '2'
                ],
                [
                    '江南街道',
                    '3'
                ],
                [
                    '渡舟街道',
                    '4'
                ],
                [
                    '双龙镇',
                    '5'
                ],
                [
                    '龙河镇',
                    '6'
                ],
                [
                    '长寿湖镇',
                    '7'
                ],
                [
                    '云台镇',
                    '8'
                ],
                [
                    '葛兰镇',
                    '9'
                ],
                [
                    '但渡镇',
                    '10'
                ],
                [
                    '邻封镇',
                    '11'
                ],
                [
                    '云集镇',
                    '12'
                ],
                [
                    '海棠镇',
                    '13'
                ],
                [
                    '石堰镇',
                    '14'
                ],
                [
                    '新市镇',
                    '15'
                ],
                [
                    '八颗镇',
                    '16'
                ],
                [
                    '洪湖镇',
                    '17'
                ],
                [
                    '万顺镇',
                    '18'
                ]
            ]
        }, cfg)]);
    }
});