/*
 * File: app/store/treestoreApplyRecl.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.treestoreApplyRecl', {
    extend: 'Ext.data.TreeStore',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'treestoreApplyRecl',
            proxy: {
                type: 'memory',
                data: [
                    {
                        id: 401,
                        text: '填写复垦申请表',
                        view: 'MyApp.view.FillReclApplicationPanel',
                        leaf: true,
                        
                    },
                    {
                        id: 402,
                        text: '上传权利证明文件',
                        view: 'MyApp.view.UploadRightDoctPanel',
                        leaf: true,
                        
                    },
                    {
                        id: 403,
                        text: '撤销及修改申请',
                        view: 'MyApp.view.ViewApplicationInfoPanel',
                        leaf: true,
                        
                    },
                    {
                        id: 404,
                        text: '审核申请',
                        view: 'MyApp.view.CancelModifyApplyPanel',
                        leaf: true,
                        
                    },
                    {
                        id: 405,
                        text: '查看审核状态',
                        view: 'MyApp.view.ReportReclApplyPanel',
                        leaf: true,
                        
                    }
                ]
            },
            fields: [
                {
                    name: 'id'
                },
                {
                    name: 'text'
                },
                {
                    name: 'view'
                }
            ]
        }, cfg)]);
    }
});