package cn.edu.bnu.land.model;

// Generated 2014-4-4 15:27:03 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * AbnmDktranssupervision generated by hbm2java
 */
public class AbnmDktranssupervision implements java.io.Serializable {

	private Integer abdkId;
	private String dkTbid;
	private String dkArea;
	private String projectId;
	private String projectName;
	private String zldwmc;
	private String dlmc;
	private String areaCode;
	private String abdkSeller;
	private String abdkBuyer;
	private String abdkSlope;
	private String abdkSlopevariance;
	private String abdkBx;
	private String abdkBy;
	private String abdkAx;
	private String abdkAy;
	private String abdkBprice;
	private String abdkAarea;
	private String abdkAprice;
	private String dgjj;
	private String dgcl;
	private Date abdkWarningtime;
	private String abdkIswarning;
	private String abdkIsnormal;
	private String abdkRisklevel;
	private String abdkOpinion;
	private String abdkDocpath;
	private String abdkHtmlpath;
	private String abdkIstowhole;
	private Date abdkTowholetime;

	public AbnmDktranssupervision() {
	}

	public AbnmDktranssupervision(String dkTbid, String dkArea,
			String projectId, String projectName, String zldwmc, String dlmc,
			String areaCode, String abdkSeller, String abdkBuyer,
			String abdkSlope, String abdkSlopevariance, String abdkBx,
			String abdkBy, String abdkAx, String abdkAy, String abdkBprice,
			String abdkAarea, String abdkAprice, String dgjj, String dgcl,
			Date abdkWarningtime, String abdkIswarning, String abdkIsnormal,
			String abdkRisklevel, String abdkOpinion, String abdkDocpath,
			String abdkHtmlpath, String abdkIstowhole, Date abdkTowholetime) {
		this.dkTbid = dkTbid;
		this.dkArea = dkArea;
		this.projectId = projectId;
		this.projectName = projectName;
		this.zldwmc = zldwmc;
		this.dlmc = dlmc;
		this.areaCode = areaCode;
		this.abdkSeller = abdkSeller;
		this.abdkBuyer = abdkBuyer;
		this.abdkSlope = abdkSlope;
		this.abdkSlopevariance = abdkSlopevariance;
		this.abdkBx = abdkBx;
		this.abdkBy = abdkBy;
		this.abdkAx = abdkAx;
		this.abdkAy = abdkAy;
		this.abdkBprice = abdkBprice;
		this.abdkAarea = abdkAarea;
		this.abdkAprice = abdkAprice;
		this.dgjj = dgjj;
		this.dgcl = dgcl;
		this.abdkWarningtime = abdkWarningtime;
		this.abdkIswarning = abdkIswarning;
		this.abdkIsnormal = abdkIsnormal;
		this.abdkRisklevel = abdkRisklevel;
		this.abdkOpinion = abdkOpinion;
		this.abdkDocpath = abdkDocpath;
		this.abdkHtmlpath = abdkHtmlpath;
		this.abdkIstowhole = abdkIstowhole;
		this.abdkTowholetime = abdkTowholetime;
	}

	public Integer getAbdkId() {
		return this.abdkId;
	}

	public void setAbdkId(Integer abdkId) {
		this.abdkId = abdkId;
	}

	public String getDkTbid() {
		return this.dkTbid;
	}

	public void setDkTbid(String dkTbid) {
		this.dkTbid = dkTbid;
	}

	public String getDkArea() {
		return this.dkArea;
	}

	public void setDkArea(String dkArea) {
		this.dkArea = dkArea;
	}

	public String getProjectId() {
		return this.projectId;
	}

	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getZldwmc() {
		return this.zldwmc;
	}

	public void setZldwmc(String zldwmc) {
		this.zldwmc = zldwmc;
	}

	public String getDlmc() {
		return this.dlmc;
	}

	public void setDlmc(String dlmc) {
		this.dlmc = dlmc;
	}

	public String getAreaCode() {
		return this.areaCode;
	}

	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode;
	}

	public String getAbdkSeller() {
		return this.abdkSeller;
	}

	public void setAbdkSeller(String abdkSeller) {
		this.abdkSeller = abdkSeller;
	}

	public String getAbdkBuyer() {
		return this.abdkBuyer;
	}

	public void setAbdkBuyer(String abdkBuyer) {
		this.abdkBuyer = abdkBuyer;
	}

	public String getAbdkSlope() {
		return this.abdkSlope;
	}

	public void setAbdkSlope(String abdkSlope) {
		this.abdkSlope = abdkSlope;
	}

	public String getAbdkSlopevariance() {
		return this.abdkSlopevariance;
	}

	public void setAbdkSlopevariance(String abdkSlopevariance) {
		this.abdkSlopevariance = abdkSlopevariance;
	}

	public String getAbdkBx() {
		return this.abdkBx;
	}

	public void setAbdkBx(String abdkBx) {
		this.abdkBx = abdkBx;
	}

	public String getAbdkBy() {
		return this.abdkBy;
	}

	public void setAbdkBy(String abdkBy) {
		this.abdkBy = abdkBy;
	}

	public String getAbdkAx() {
		return this.abdkAx;
	}

	public void setAbdkAx(String abdkAx) {
		this.abdkAx = abdkAx;
	}

	public String getAbdkAy() {
		return this.abdkAy;
	}

	public void setAbdkAy(String abdkAy) {
		this.abdkAy = abdkAy;
	}

	public String getAbdkBprice() {
		return this.abdkBprice;
	}

	public void setAbdkBprice(String abdkBprice) {
		this.abdkBprice = abdkBprice;
	}

	public String getAbdkAarea() {
		return this.abdkAarea;
	}

	public void setAbdkAarea(String abdkAarea) {
		this.abdkAarea = abdkAarea;
	}

	public String getAbdkAprice() {
		return this.abdkAprice;
	}

	public void setAbdkAprice(String abdkAprice) {
		this.abdkAprice = abdkAprice;
	}

	public String getDgjj() {
		return this.dgjj;
	}

	public void setDgjj(String dgjj) {
		this.dgjj = dgjj;
	}

	public String getDgcl() {
		return this.dgcl;
	}

	public void setDgcl(String dgcl) {
		this.dgcl = dgcl;
	}

	public Date getAbdkWarningtime() {
		return this.abdkWarningtime;
	}

	public void setAbdkWarningtime(Date abdkWarningtime) {
		this.abdkWarningtime = abdkWarningtime;
	}

	public String getAbdkIswarning() {
		return this.abdkIswarning;
	}

	public void setAbdkIswarning(String abdkIswarning) {
		this.abdkIswarning = abdkIswarning;
	}

	public String getAbdkIsnormal() {
		return this.abdkIsnormal;
	}

	public void setAbdkIsnormal(String abdkIsnormal) {
		this.abdkIsnormal = abdkIsnormal;
	}

	public String getAbdkRisklevel() {
		return this.abdkRisklevel;
	}

	public void setAbdkRisklevel(String abdkRisklevel) {
		this.abdkRisklevel = abdkRisklevel;
	}

	public String getAbdkOpinion() {
		return this.abdkOpinion;
	}

	public void setAbdkOpinion(String abdkOpinion) {
		this.abdkOpinion = abdkOpinion;
	}

	public String getAbdkDocpath() {
		return this.abdkDocpath;
	}

	public void setAbdkDocpath(String abdkDocpath) {
		this.abdkDocpath = abdkDocpath;
	}

	public String getAbdkHtmlpath() {
		return this.abdkHtmlpath;
	}

	public void setAbdkHtmlpath(String abdkHtmlpath) {
		this.abdkHtmlpath = abdkHtmlpath;
	}

	public String getAbdkIstowhole() {
		return this.abdkIstowhole;
	}

	public void setAbdkIstowhole(String abdkIstowhole) {
		this.abdkIstowhole = abdkIstowhole;
	}

	public Date getAbdkTowholetime() {
		return this.abdkTowholetime;
	}

	public void setAbdkTowholetime(Date abdkTowholetime) {
		this.abdkTowholetime = abdkTowholetime;
	}

}
