package cn.edu.bnu.land.model;

// Generated 2014-4-14 10:49:36 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * BenefitStatnh generated by hbm2java
 */
public class BenefitStatnh implements java.io.Serializable {

	private Integer xh;
	private Date lzsj;
	private String nhxm;
	private String yydkbh;
	private Integer lzl;
	private Integer lzlbl;
	private Integer sy;
	private Integer sybl;

	public BenefitStatnh() {
	}

	public BenefitStatnh(Date lzsj, String nhxm, String yydkbh, Integer lzl,
			Integer lzlbl, Integer sy, Integer sybl) {
		this.lzsj = lzsj;
		this.nhxm = nhxm;
		this.yydkbh = yydkbh;
		this.lzl = lzl;
		this.lzlbl = lzlbl;
		this.sy = sy;
		this.sybl = sybl;
	}

	public Integer getXh() {
		return this.xh;
	}

	public void setXh(Integer xh) {
		this.xh = xh;
	}

	public Date getLzsj() {
		return this.lzsj;
	}

	public void setLzsj(Date lzsj) {
		this.lzsj = lzsj;
	}

	public String getNhxm() {
		return this.nhxm;
	}

	public void setNhxm(String nhxm) {
		this.nhxm = nhxm;
	}

	public String getYydkbh() {
		return this.yydkbh;
	}

	public void setYydkbh(String yydkbh) {
		this.yydkbh = yydkbh;
	}

	public Integer getLzl() {
		return this.lzl;
	}

	public void setLzl(Integer lzl) {
		this.lzl = lzl;
	}

	public Integer getLzlbl() {
		return this.lzlbl;
	}

	public void setLzlbl(Integer lzlbl) {
		this.lzlbl = lzlbl;
	}

	public Integer getSy() {
		return this.sy;
	}

	public void setSy(Integer sy) {
		this.sy = sy;
	}

	public Integer getSybl() {
		return this.sybl;
	}

	public void setSybl(Integer sybl) {
		this.sybl = sybl;
	}

}
