package cn.edu.bnu.land.model;

// Generated 2014-5-17 21:50:16 by Hibernate Tools 4.0.0

/**
 * BenefitCanshushou generated by hbm2java
 */
public class BenefitCanshushou implements java.io.Serializable {

	private int xh;
	private Integer dzzcts;
	private Integer cbzgjg;
	private Integer jsbl;
	private Integer zfbl;
	private Integer nhbl;
	private Integer zxbl;
	private Integer zdqsx;
	private Integer jb;

	public BenefitCanshushou() {
	}

	public BenefitCanshushou(int xh) {
		this.xh = xh;
	}

	public BenefitCanshushou(int xh, Integer dzzcts, Integer cbzgjg,
			Integer jsbl, Integer zfbl, Integer nhbl, Integer zxbl,
			Integer zdqsx, Integer jb) {
		this.xh = xh;
		this.dzzcts = dzzcts;
		this.cbzgjg = cbzgjg;
		this.jsbl = jsbl;
		this.zfbl = zfbl;
		this.nhbl = nhbl;
		this.zxbl = zxbl;
		this.zdqsx = zdqsx;
		this.jb = jb;
	}

	public int getXh() {
		return this.xh;
	}

	public void setXh(int xh) {
		this.xh = xh;
	}

	public Integer getDzzcts() {
		return this.dzzcts;
	}

	public void setDzzcts(Integer dzzcts) {
		this.dzzcts = dzzcts;
	}

	public Integer getCbzgjg() {
		return this.cbzgjg;
	}

	public void setCbzgjg(Integer cbzgjg) {
		this.cbzgjg = cbzgjg;
	}

	public Integer getJsbl() {
		return this.jsbl;
	}

	public void setJsbl(Integer jsbl) {
		this.jsbl = jsbl;
	}

	public Integer getZfbl() {
		return this.zfbl;
	}

	public void setZfbl(Integer zfbl) {
		this.zfbl = zfbl;
	}

	public Integer getNhbl() {
		return this.nhbl;
	}

	public void setNhbl(Integer nhbl) {
		this.nhbl = nhbl;
	}

	public Integer getZxbl() {
		return this.zxbl;
	}

	public void setZxbl(Integer zxbl) {
		this.zxbl = zxbl;
	}

	public Integer getZdqsx() {
		return this.zdqsx;
	}

	public void setZdqsx(Integer zdqsx) {
		this.zdqsx = zdqsx;
	}

	public Integer getJb() {
		return this.jb;
	}

	public void setJb(Integer jb) {
		this.jb = jb;
	}

}
