package cn.edu.bnu.land.model;

// Generated 2014-5-9 9:49:33 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * BenefitAssign generated by hbm2java
 */
public class BenefitAssign implements java.io.Serializable {

	private Integer xh;
	private String htbh;
	private Date jysj;
	private Double jyl;
	private String jyqy;
	private String gmqymc;
	private String qyxz;
	private Double qyzczj;
	private Double dj;
	private Double je;

	public BenefitAssign() {
	}

	public BenefitAssign(String htbh, Date jysj, Double jyl, String jyqy,
			String gmqymc, String qyxz, Double qyzczj, Double dj, Double je) {
		this.htbh = htbh;
		this.jysj = jysj;
		this.jyl = jyl;
		this.jyqy = jyqy;
		this.gmqymc = gmqymc;
		this.qyxz = qyxz;
		this.qyzczj = qyzczj;
		this.dj = dj;
		this.je = je;
	}

	public Integer getXh() {
		return this.xh;
	}

	public void setXh(Integer xh) {
		this.xh = xh;
	}

	public String getHtbh() {
		return this.htbh;
	}

	public void setHtbh(String htbh) {
		this.htbh = htbh;
	}

	public Date getJysj() {
		return this.jysj;
	}

	public void setJysj(Date jysj) {
		this.jysj = jysj;
	}

	public Double getJyl() {
		return this.jyl;
	}

	public void setJyl(Double jyl) {
		this.jyl = jyl;
	}

	public String getJyqy() {
		return this.jyqy;
	}

	public void setJyqy(String jyqy) {
		this.jyqy = jyqy;
	}

	public String getGmqymc() {
		return this.gmqymc;
	}

	public void setGmqymc(String gmqymc) {
		this.gmqymc = gmqymc;
	}

	public String getQyxz() {
		return this.qyxz;
	}

	public void setQyxz(String qyxz) {
		this.qyxz = qyxz;
	}

	public Double getQyzczj() {
		return this.qyzczj;
	}

	public void setQyzczj(Double qyzczj) {
		this.qyzczj = qyzczj;
	}

	public Double getDj() {
		return this.dj;
	}

	public void setDj(Double dj) {
		this.dj = dj;
	}

	public Double getJe() {
		return this.je;
	}

	public void setJe(Double je) {
		this.je = je;
	}

}
