package cn.edu.bnu.land.model;

// Generated 2014-3-26 15:08:03 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * BenefitAnalyze generated by hbm2java
 */
public class BenefitAnalyze implements java.io.Serializable {

	private BenefitAnalyzeId id;
	private int xh;
	private String yydkbh;
	private Integer lzl;
	private Integer nhsy;
	private String sjdkbh;
	private String cyrw;
	private Date cysj;
	private Integer jssy;

	public BenefitAnalyze() {
	}

	public BenefitAnalyze(BenefitAnalyzeId id, int xh) {
		this.id = id;
		this.xh = xh;
	}

	public BenefitAnalyze(BenefitAnalyzeId id, int xh, String yydkbh,
			Integer lzl, Integer nhsy, String sjdkbh, String cyrw, Date cysj,
			Integer jssy) {
		this.id = id;
		this.xh = xh;
		this.yydkbh = yydkbh;
		this.lzl = lzl;
		this.nhsy = nhsy;
		this.sjdkbh = sjdkbh;
		this.cyrw = cyrw;
		this.cysj = cysj;
		this.jssy = jssy;
	}

	public BenefitAnalyzeId getId() {
		return this.id;
	}

	public void setId(BenefitAnalyzeId id) {
		this.id = id;
	}

	public int getXh() {
		return this.xh;
	}

	public void setXh(int xh) {
		this.xh = xh;
	}

	public String getYydkbh() {
		return this.yydkbh;
	}

	public void setYydkbh(String yydkbh) {
		this.yydkbh = yydkbh;
	}

	public Integer getLzl() {
		return this.lzl;
	}

	public void setLzl(Integer lzl) {
		this.lzl = lzl;
	}

	public Integer getNhsy() {
		return this.nhsy;
	}

	public void setNhsy(Integer nhsy) {
		this.nhsy = nhsy;
	}

	public String getSjdkbh() {
		return this.sjdkbh;
	}

	public void setSjdkbh(String sjdkbh) {
		this.sjdkbh = sjdkbh;
	}

	public String getCyrw() {
		return this.cyrw;
	}

	public void setCyrw(String cyrw) {
		this.cyrw = cyrw;
	}

	public Date getCysj() {
		return this.cysj;
	}

	public void setCysj(Date cysj) {
		this.cysj = cysj;
	}

	public Integer getJssy() {
		return this.jssy;
	}

	public void setJssy(Integer jssy) {
		this.jssy = jssy;
	}

}
