package cn.edu.bnu.land.model;

// Generated 2015-4-17 17:01:56 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * DbBackuprecord generated by hbm2java
 */
public class DbBackuprecord implements java.io.Serializable {

	private Integer id;
	private Date bkdate;
	private Integer size;
	private String description;

	public DbBackuprecord() {
	}

	public DbBackuprecord(Date bkdate, Integer size, String description) {
		this.bkdate = bkdate;
		this.size = size;
		this.description = description;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getBkdate() {
		return this.bkdate;
	}

	public void setBkdate(Date bkdate) {
		this.bkdate = bkdate;
	}

	public Integer getSize() {
		return this.size;
	}

	public void setSize(Integer size) {
		this.size = size;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
