package cn.edu.bnu.land.model;

// Generated 2014-3-11 20:56:01 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * InfoArticle generated by hbm2java
 */
public class InfoArticle implements java.io.Serializable {

	private Integer articleId;
	private String articleName;
	private String articleContent;
	private Integer channelId;
	private String articleIsrecycle;
	private Date articlePublishtime;
	private String articleSource;
	private String articleAuthor;
	private String articleIsdraft;
	private Integer commentNum;
	private String areaCode;
	private String isMailpush;
	private String isSmspush;
	private String coordinate;

	public InfoArticle() {
	}

	public InfoArticle(String articleName, String articleContent,
			Integer channelId, String articleIsrecycle,
			Date articlePublishtime, String articleSource,
			String articleAuthor, String articleIsdraft, Integer commentNum,
			String areaCode, String isMailpush, String isSmspush,
			String coordinate) {
		this.articleName = articleName;
		this.articleContent = articleContent;
		this.channelId = channelId;
		this.articleIsrecycle = articleIsrecycle;
		this.articlePublishtime = articlePublishtime;
		this.articleSource = articleSource;
		this.articleAuthor = articleAuthor;
		this.articleIsdraft = articleIsdraft;
		this.commentNum = commentNum;
		this.areaCode = areaCode;
		this.isMailpush = isMailpush;
		this.isSmspush = isSmspush;
		this.coordinate = coordinate;
	}

	public Integer getArticleId() {
		return this.articleId;
	}

	public void setArticleId(Integer articleId) {
		this.articleId = articleId;
	}

	public String getArticleName() {
		return this.articleName;
	}

	public void setArticleName(String articleName) {
		this.articleName = articleName;
	}

	public String getArticleContent() {
		return this.articleContent;
	}

	public void setArticleContent(String articleContent) {
		this.articleContent = articleContent;
	}

	public Integer getChannelId() {
		return this.channelId;
	}

	public void setChannelId(Integer channelId) {
		this.channelId = channelId;
	}

	public String getArticleIsrecycle() {
		return this.articleIsrecycle;
	}

	public void setArticleIsrecycle(String articleIsrecycle) {
		this.articleIsrecycle = articleIsrecycle;
	}

	public Date getArticlePublishtime() {
		return this.articlePublishtime;
	}

	public void setArticlePublishtime(Date articlePublishtime) {
		this.articlePublishtime = articlePublishtime;
	}

	public String getArticleSource() {
		return this.articleSource;
	}

	public void setArticleSource(String articleSource) {
		this.articleSource = articleSource;
	}

	public String getArticleAuthor() {
		return this.articleAuthor;
	}

	public void setArticleAuthor(String articleAuthor) {
		this.articleAuthor = articleAuthor;
	}

	public String getArticleIsdraft() {
		return this.articleIsdraft;
	}

	public void setArticleIsdraft(String articleIsdraft) {
		this.articleIsdraft = articleIsdraft;
	}

	public Integer getCommentNum() {
		return this.commentNum;
	}

	public void setCommentNum(Integer commentNum) {
		this.commentNum = commentNum;
	}

	public String getAreaCode() {
		return this.areaCode;
	}

	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode;
	}

	public String getIsMailpush() {
		return this.isMailpush;
	}

	public void setIsMailpush(String isMailpush) {
		this.isMailpush = isMailpush;
	}

	public String getIsSmspush() {
		return this.isSmspush;
	}

	public void setIsSmspush(String isSmspush) {
		this.isSmspush = isSmspush;
	}

	public String getCoordinate() {
		return this.coordinate;
	}

	public void setCoordinate(String coordinate) {
		this.coordinate = coordinate;
	}

}
