package cn.edu.bnu.land.model;

// Generated 2014-4-24 21:36:09 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * ProjectYqProgress generated by hbm2java
 */
public class ProjectYqProgress implements java.io.Serializable {

	private Integer recordId;
	private String projectName;
	private String projectId;
	private Date monitorTime;
	private String rwId;
	private Float ypercentPz;
	private Float ypercentSl;
	private Float ypercentDl;
	private Integer finishdateLimit;
	private Boolean isSended;
	private Boolean isFinished;
	private Date finishTime;
	private Float ppercentPz;
	private Float ppercentSl;
	private Float ppercentDl;

	public ProjectYqProgress() {
	}

	public ProjectYqProgress(String projectName, String projectId,
			Date monitorTime, String rwId, Float ypercentPz, Float ypercentSl,
			Float ypercentDl, Integer finishdateLimit, Boolean isSended,
			Boolean isFinished, Date finishTime, Float ppercentPz,
			Float ppercentSl, Float ppercentDl) {
		this.projectName = projectName;
		this.projectId = projectId;
		this.monitorTime = monitorTime;
		this.rwId = rwId;
		this.ypercentPz = ypercentPz;
		this.ypercentSl = ypercentSl;
		this.ypercentDl = ypercentDl;
		this.finishdateLimit = finishdateLimit;
		this.isSended = isSended;
		this.isFinished = isFinished;
		this.finishTime = finishTime;
		this.ppercentPz = ppercentPz;
		this.ppercentSl = ppercentSl;
		this.ppercentDl = ppercentDl;
	}

	public Integer getRecordId() {
		return this.recordId;
	}

	public void setRecordId(Integer recordId) {
		this.recordId = recordId;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getProjectId() {
		return this.projectId;
	}

	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	public Date getMonitorTime() {
		return this.monitorTime;
	}

	public void setMonitorTime(Date monitorTime) {
		this.monitorTime = monitorTime;
	}

	public String getRwId() {
		return this.rwId;
	}

	public void setRwId(String rwId) {
		this.rwId = rwId;
	}

	public Float getYpercentPz() {
		return this.ypercentPz;
	}

	public void setYpercentPz(Float ypercentPz) {
		this.ypercentPz = ypercentPz;
	}

	public Float getYpercentSl() {
		return this.ypercentSl;
	}

	public void setYpercentSl(Float ypercentSl) {
		this.ypercentSl = ypercentSl;
	}

	public Float getYpercentDl() {
		return this.ypercentDl;
	}

	public void setYpercentDl(Float ypercentDl) {
		this.ypercentDl = ypercentDl;
	}

	public Integer getFinishdateLimit() {
		return this.finishdateLimit;
	}

	public void setFinishdateLimit(Integer finishdateLimit) {
		this.finishdateLimit = finishdateLimit;
	}

	public Boolean getIsSended() {
		return this.isSended;
	}

	public void setIsSended(Boolean isSended) {
		this.isSended = isSended;
	}

	public Boolean getIsFinished() {
		return this.isFinished;
	}

	public void setIsFinished(Boolean isFinished) {
		this.isFinished = isFinished;
	}

	public Date getFinishTime() {
		return this.finishTime;
	}

	public void setFinishTime(Date finishTime) {
		this.finishTime = finishTime;
	}

	public Float getPpercentPz() {
		return this.ppercentPz;
	}

	public void setPpercentPz(Float ppercentPz) {
		this.ppercentPz = ppercentPz;
	}

	public Float getPpercentSl() {
		return this.ppercentSl;
	}

	public void setPpercentSl(Float ppercentSl) {
		this.ppercentSl = ppercentSl;
	}

	public Float getPpercentDl() {
		return this.ppercentDl;
	}

	public void setPpercentDl(Float ppercentDl) {
		this.ppercentDl = ppercentDl;
	}

}
