package cn.edu.bnu.land.model;

// Generated 2014-5-6 9:39:29 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * UOptLog generated by hbm2java
 */
public class UOptLog implements java.io.Serializable {

	private String id;
	private int userId;
	private Date executTime;
	private Integer taskId;
	private String ipAddr;

	public UOptLog() {
	}

	public UOptLog(String id, int userId) {
		this.id = id;
		this.userId = userId;
	}

	public UOptLog(String id, int userId, Date executTime, Integer taskId,
			String ipAddr) {
		this.id = id;
		this.userId = userId;
		this.executTime = executTime;
		this.taskId = taskId;
		this.ipAddr = ipAddr;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public Date getExecutTime() {
		return this.executTime;
	}

	public void setExecutTime(Date executTime) {
		this.executTime = executTime;
	}

	public Integer getTaskId() {
		return this.taskId;
	}

	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}

	public String getIpAddr() {
		return this.ipAddr;
	}

	public void setIpAddr(String ipAddr) {
		this.ipAddr = ipAddr;
	}

}
