package cn.edu.bnu.land.model;

// Generated 2014-6-26 22:16:01 by Hibernate Tools 4.0.0

/**
 * URightInfo generated by hbm2java
 */
public class URightInfo implements java.io.Serializable {

	private String rightId;
	private String rightName;
	private String rightIndex;
	private String url;
	private Boolean enabled;
	private String description;

	public URightInfo() {
	}

	public URightInfo(String rightId, String rightName) {
		this.rightId = rightId;
		this.rightName = rightName;
	}

	public URightInfo(String rightId, String rightName, String rightIndex,
			String url, Boolean enabled, String description) {
		this.rightId = rightId;
		this.rightName = rightName;
		this.rightIndex = rightIndex;
		this.url = url;
		this.enabled = enabled;
		this.description = description;
	}

	public String getRightId() {
		return this.rightId;
	}

	public void setRightId(String rightId) {
		this.rightId = rightId;
	}

	public String getRightName() {
		return this.rightName;
	}

	public void setRightName(String rightName) {
		this.rightName = rightName;
	}

	public String getRightIndex() {
		return this.rightIndex;
	}

	public void setRightIndex(String rightIndex) {
		this.rightIndex = rightIndex;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
