package cn.edu.bnu.land.model;

// Generated 2014-5-6 9:39:29 by Hibernate Tools 4.0.0

/**
 * UTaskCode generated by hbm2java
 */
public class UTaskCode implements java.io.Serializable {

	private String taskId;
	private String taskName;
	private Byte taskLevel;
	private String description;

	public UTaskCode() {
	}

	public UTaskCode(String taskId, String taskName) {
		this.taskId = taskId;
		this.taskName = taskName;
	}

	public UTaskCode(String taskId, String taskName, Byte taskLevel,
			String description) {
		this.taskId = taskId;
		this.taskName = taskName;
		this.taskLevel = taskLevel;
		this.description = description;
	}

	public String getTaskId() {
		return this.taskId;
	}

	public void setTaskId(String taskId) {
		this.taskId = taskId;
	}

	public String getTaskName() {
		return this.taskName;
	}

	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}

	public Byte getTaskLevel() {
		return this.taskLevel;
	}

	public void setTaskLevel(Byte taskLevel) {
		this.taskLevel = taskLevel;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
