/*
 * File: app/model/db_users.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.db_users', {
    extend: 'Ext.data.Model',
    alias: 'model.db_users',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'userid'
        },
        {
            name: 'username',
            type: 'string'
        },
        {
            name: 'password',
            type: 'string'
        },
        {
            name: 'enabled',
            type: 'boolean'
        },
        {
            name: 'registerdate',
            type: 'date'
        },
        {
            name: 'truename'
        },
        {
            name: 'email',
            type: 'string'
        },
        {
            name: 'mobilenum',
            type: 'string'
        },
        {
            name: 'phonenum',
            type: 'string'
        },
        {
            name: 'description',
            type: 'auto'
        }
    ]
});