/*
 * File: app/model/ShouyiAlarm_Canshu.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.ShouyiAlarm_Canshu', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'dzzcts',
            type: 'int'
        },
        {
            name: 'cbzgjg',
            type: 'int'
        },
        {
            name: 'jsbl',
            type: 'int'
        },
        {
            name: 'zfbl',
            type: 'int'
        },
        {
            name: 'nhbl',
            type: 'int'
        },
        {
            name: 'zdqsx',
            type: 'int'
        },
        {
            name: 'xh',
            type: 'int'
        },
        {
            name: 'jb',
            type: 'int'
        }
    ]
});