/*
 * File: app/view/abnmDkTransSupervisionTab.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.abnmDkTransSupervisionTab', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.abnmDkTransSupervisionTab',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.RowNumberer',
        'Ext.grid.column.Date',
        'Ext.grid.View',
        'Ext.selection.CheckboxModel',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date',
        'Ext.button.Button',
        'Ext.toolbar.Paging'
    ],

    height: 750,
    id: 'abnmDkTransSupervisionTab',
    layout: 'fit',
    title: '交易>>交易风险预警',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    id: 'abnmDkTransSupervisionGrid',
                    collapsible: false,
                    title: '',
                    forceFit: true,
                    store: 'abnmDkTransSupervisionStore',
                    columns: [
                        {
                            xtype: 'rownumberer',
                            width: 47,
                            text: '记录号'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'dkTbid',
                            text: '地块编号',
                            tooltip: ''
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'projectId',
                            text: '项目编号',
                            tooltip: ''
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'projectName',
                            text: '项目名称',
                            tooltip: ''
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'abdkIswarning',
                            text: '是否预警'
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'abdkWarningtime',
                            text: '预警时间',
                            format: 'Y-m-d'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'abdkIsnormal',
                            text: '交易是否异常'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'abdkRisklevel',
                            text: '风险等级'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'abdkIstowhole',
                            text: '是否提交异常信息'
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'abdkTowholetime',
                            text: '提交时间',
                            format: 'Y-m-d'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'abdkOpinion',
                            text: '备注'
                        }
                    ],
                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                    }),
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            frame: false,
                            enableOverflow: true,
                            items: [
                                {
                                    xtype: 'combobox',
                                    id: 'provinceSelected',
                                    name: 'provinceSelected',
                                    emptyText: '请选择省',
                                    displayField: 'areaName',
                                    store: 'abnmProvinceStore',
                                    valueField: 'areaCode',
                                    listeners: {
                                        select: {
                                            fn: me.onProvinceSelectedSelect,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'combobox',
                                    id: 'citySelected',
                                    name: 'citySelected',
                                    emptyText: '请选择市',
                                    displayField: 'areaName',
                                    store: 'abnmCityStore',
                                    valueField: 'areaCode',
                                    listeners: {
                                        select: {
                                            fn: me.onCitySelectedSelect,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'combobox',
                                    id: 'countySelected',
                                    name: 'countySelected',
                                    emptyText: '请选择县',
                                    displayField: 'areaName',
                                    store: 'abnmCountyStore',
                                    valueField: 'areaCode'
                                },
                                {
                                    xtype: 'datefield',
                                    id: 'searchDateabts',
                                    width: 204,
                                    fieldLabel: '时间',
                                    labelWidth: 70,
                                    format: 'Y-m-d'
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'searchKeywordabts',
                                    width: 211,
                                    fieldLabel: '',
                                    labelWidth: 50,
                                    emptyText: '请输入搜索关键字'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        var getDate = Ext.util.Format.date(Ext.getCmp('searchDateabts').getValue(),'Y-m-d');
                                        var getKeyword = Ext.getCmp('searchKeywordabts').getValue();
                                        var getProvince = Ext.getCmp('provinceSelected').getValue();
                                        var getCity = Ext.getCmp('citySelected').getValue();
                                        var getCounty = Ext.getCmp('countySelected').getValue();



                                        var mystore=Ext.StoreMgr.get('abnmDkTransSupervisionStore'); //获得store对象



                                        //在load事件中添加参数
                                        //mystore.load(
                                        //{params:{
                                        //    start:"0",
                                        //    limit:"25",
                                        //    searchKeyword:getKeyword,
                                        //    searchDate:getDate,
                                        //    province:getProvince,
                                        //    city:getCity,
                                        //    county:getCounty
                                        //}
                                        //}
                                        //);





                                        mystore.on('beforeload',function(store,options){

                                            var new_params = {
                                                searchKeyword:getKeyword,
                                                searchDate:getDate,
                                                province:getProvince,
                                                city:getCity,
                                                county:getCounty
                                            };

                                            Ext.apply(store.proxy.extraParams,new_params);
                                        });

                                        mystore.load(
                                        {
                                            params:{
                                                start:"0",
                                                limit:"25"
                                            }
                                        }
                                        );
                                    },
                                    icon: 'images/file_view0.png',
                                    text: '搜索'
                                }
                            ]
                        },
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            frame: false,
                            enableOverflow: true,
                            items: [
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        var win = Ext.widget('abnmDKTSAddTab');
                                        win.show();
                                    },
                                    icon: 'images/file_view0.png',
                                    text: '信息录入'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        var grid = Ext.getCmp('abnmDkTransSupervisionGrid');
                                        //var gird = this.down('grid');
                                        var record = grid.getSelectionModel().getSelection();

                                        if(record.length === 0){
                                            Ext.Msg.alert('提示','请先选择您要操作的行！');
                                            return;

                                        }else{

                                            var  ids =new Array(record.length);
                                            for(var i = 0;i<record.length;i++){
                                                ids[i] = record[i].get("abdkId");

                                            }
                                            //Ext.Msg.alert('提示',ids);



                                            Ext.Ajax.request({
                                                url:'delete_abdkByIds',
                                                params:{ids:ids},
                                                success:function(response){
                                                    Ext.Msg.alert('成功','删除成功');
                                                    var mystore = Ext.StoreMgr.get('abnmDkTransSupervisionStore');
                                                    mystore.load();
                                                },
                                                failure:function(response){
                                                    Ext.Msg.alert('失败','删除失败');
                                                }

                                            });


                                        }
                                    },
                                    icon: 'images/file_view0.png',
                                    text: '删除'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        var grid = Ext.getCmp('abnmDkTransSupervisionGrid');
                                        //var gird = this.down('grid');
                                        var record = grid.getSelectionModel().getSelection();

                                        if(record.length != 1){
                                            Ext.Msg.alert('提示','请先选择一行数据进行操作！');
                                            return;

                                        }else{

                                            var  abdkId =record[0].get("abdkId");




                                            Ext.Ajax.request({
                                                url:'calculate_abdkById',
                                                params:{abdkId:abdkId},
                                                waitMsg: '正在计算，请稍后...',
                                                success:function(response){
                                                    Ext.Msg.alert('成功','异常预警成功');
                                                    var mystore = Ext.StoreMgr.get('abnmDkTransSupervisionStore');
                                                    mystore.load();
                                                },
                                                failure:function(response){
                                                    Ext.Msg.alert('失败','异常预警失败');
                                                }

                                            });


                                        }
                                    },
                                    icon: 'images/file_view0.png',
                                    text: '交易风险预警'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        var grid = Ext.getCmp('abnmDkTransSupervisionGrid');

                                        var record = grid.getSelectionModel().getSelection();

                                        if(record.length != 1 || record[0].get("abdkIsnormal")!= '是'){
                                            Ext.Msg.alert('提示','请先选择一条“是否异常”为“是”的信息！<br>若“是否异常”显示为空，请先进行“交易风险预警”！');
                                            return;

                                        }else{



                                            var abnmWSAddTabwin = Ext.widget('abnmWSAddTab');
                                            console.log(abnmWSAddTabwin);

                                            abnmWSAddTabwin.show();

                                            Ext.getCmp('abwsClassAdd').setValue('交易预警');
                                            Ext.getCmp('projectIdAdd').setValue(record[0].get("projectId"));
                                            Ext.getCmp('abwsTitleAdd').setValue(record[0].get("dkTbid")+" 交易预警结果显示存在风险");
                                            Ext.getCmp('abwsContentAdd').setValue(record[0].get("dkTbid")+" 交易预警风险等级为 "+record[0].get("abdkRisklevel")+"。");

                                            Ext.getCmp('projectNameAdd').setValue(record[0].get("projectName"));
                                            Ext.getCmp('sourceRecordidAdd').setValue(record[0].get("abdkId"));



                                        }
                                    },
                                    icon: 'images/file_view0.png',
                                    text: '提交异常监管'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        var tabs = this.up('tabpanel');
                                        tabs.removeAll(true);
                                        tabs.add(Ext.widget('abnmDKTSmapTab'));

                                        //加入地图的js文件
                                        var head = document.getElementsByTagName('head')[0];
                                        var script= document.createElement("script");
                                        script.type = "text/javascript";
                                        script.src="map/abnmRisk_map.js";
                                        head.appendChild(script);
                                    },
                                    icon: 'images/file_view0.png',
                                    text: '交易异常预警地图'
                                }
                            ]
                        },
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            height: 36,
                            width: 360,
                            displayInfo: true,
                            store: 'abnmDkTransSupervisionStore'
                        }
                    ],
                    listeners: {
                        cellclick: {
                            fn: me.onAbnmDkTransSupervisionGridCellClick,
                            scope: me
                        }
                    }
                }
            ]
        });

        me.callParent(arguments);
    },

    onProvinceSelectedSelect: function(combo, records, eOpts) {
        var cityField=Ext.getCmp("citySelected");
        cityField.setValue('');
        var countyField=Ext.getCmp("countySelected");
        countyField.setValue('');
        var codeHead=records[0].get('areaCode');
        Ext.Ajax.request({
            url:'get_infoAreaCityList',
            params:{codeHead:codeHead},
            success:function(response){
                var mystore = Ext.StoreMgr.get('abnmCityStore');
                mystore.load(
                {
                    params:{
                        codeHead: codeHead
                    }
                }
                );
            }
        });
        var  cityStore=Ext.StoreMgr.get('abnmCityStore');//获取store对象

        //设置所在市下拉菜单的列表项的新的Store
        if(cityField.view)
        cityField.view.setStore(cityStore);




    },

    onCitySelectedSelect: function(combo, records, eOpts) {
        var countyField=Ext.getCmp("countySelected");
        countyField.setValue('');
        var codeHead=records[0].get('areaCode');
        Ext.Ajax.request({
            url:'get_infoAreaCountyList',
            params:{codeHead:codeHead},
            success:function(response){
                var mystore = Ext.StoreMgr.get('abnmCountyStore');
                mystore.load(
                {
                    params:{
                        codeHead: codeHead
                    }
                }
                );
            }
        });
        var  countyStore=Ext.StoreMgr.get('abnmCountyStore');//获取store对象
        //设置所在县下拉菜单的列表项的新的Store
        if(countyField.view)
        countyField.view.setStore(countyStore);



    },

    onAbnmDkTransSupervisionGridCellClick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {
        if(cellIndex === undefined || cellIndex < 2 ||cellIndex >8) return;

        var getDkId = record.data.abdkId;

        var getIndexId = record.data.abiId;
        var getIndexStore = Ext.StoreMgr.get('abnmIndexStore');
        getIndexStore.load({
            params:{
                dkId:record.data.abdkId
            }
        });

        var win = new Ext.Window({

            title: '查看地块详细信息',
            closable: true,
            layout: 'fit',
            jsonSubmit: true,
            items:[{
                xtype: 'form',
                width:600,
                height:600,
                layout:{
                type: 'absolute'},
                bodyPadding:10,
                jsonSubmit: true,
                items: [
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 70,
                    id: 'abdkId',
                    fieldLabel: '地块Id',
                    labelWidth: 80,
                    hidden: true,
                    name: 'abdkId'
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 70,
                    id: 'dkTbid',
                    fieldLabel: '图斑编号',
                    labelWidth: 80,
                    name: 'dkTbid'
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 130,
                    id: 'abdkSeller',
                    fieldLabel: '转让方',
                    labelWidth: 80,
                    name: 'abdkSeller'
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 160,
                    id: 'abdkBx',
                    fieldLabel: '交易前中心点坐标X',
                    labelWidth: 80,
                    name: 'abdkBx'
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 220,
                    id: 'abdkBprice',
                    fieldLabel: '交易前地块价格',
                    labelWidth: 80,
                    name: 'abdkBprice'
                },
                {
                    xtype: 'textfield',
                    x: 300,
                    y: 160,
                    id: 'abdkAx',
                    fieldLabel: '交易后中心点坐标X',
                    labelWidth: 80,
                    name: 'abdkAx'
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 260,
                    id: 'dgcl',
                    fieldLabel: '稻谷产量',
                    labelWidth: 80,
                    name: 'dgcl'
                },
                {
                    xtype: 'textfield',
                    x: 300,
                    y: 260,
                    id: 'abdkAarea',
                    fieldLabel: '交易后地块面积',
                    labelWidth: 80,
                    name: 'abdkAarea'
                },
                {
                    xtype: 'textfield',
                    x: 300,
                    y: 70,
                    id: 'dkArea',
                    fieldLabel: '图斑面积',
                    labelWidth: 80,
                    name: 'dkArea'
                },
                {
                    xtype: 'textfield',
                    x: 300,
                    y: 40,
                    id: 'areaCode',
                    fieldLabel: '所属行政区',
                    labelWidth: 80,
                    name: 'areaCode'
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 40,
                    id: 'projectId',
                    fieldLabel: '所属项目编号',
                    labelWidth: 80,
                    name: 'projectId'
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 100,
                    id: 'abdkSlope',
                    fieldLabel: '坡地',
                    labelWidth: 80,
                    name: 'abdkSlope'
                },
                {
                    xtype: 'textfield',
                    x: 300,
                    y: 100,
                    id: 'abdkSlopevariance',
                    fieldLabel: '坡度方差',
                    labelWidth: 80,
                    name: 'abdkSlopevariance'
                },
                {
                    xtype: 'textfield',
                    x: 300,
                    y: 130,
                    id: 'abdkBuyer',
                    fieldLabel: '买入方',
                    labelWidth: 80,
                    name: 'abdkBuyer'
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 190,
                    id: 'abdkBy',
                    fieldLabel: '交易前中心点坐标Y',
                    labelWidth: 80,
                    name: 'abdkBy'
                },
                {
                    xtype: 'textfield',
                    x: 300,
                    y: 220,
                    id: 'abdkAprice',
                    fieldLabel: '交易后地块价格',
                    labelWidth: 80,
                    name: 'abdkAprice'
                },
                {
                    xtype: 'textfield',
                    x: 300,
                    y: 190,
                    id: 'abdkAy',
                    fieldLabel: '交易后中心点坐标Y',
                    labelWidth: 80,
                    name: 'abdkAy'
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 290,
                    id: 'dgjj',
                    fieldLabel: '稻谷均价',
                    labelWidth: 80,
                    name: 'dgjj'
                },
                {
                    xtype: 'displayfield',
                    x: 10,
                    y: 10,
                    id: 'abdkIsnormal',
                    fieldLabel: '是否异常',
                    labelWidth: 80,
                    name: 'abdkIsnormal'
                },
                {
                    xtype: 'displayfield',
                    x: 300,
                    y: 10,
                    id: 'abdkRisklevel',
                    fieldLabel: '风险等级',
                    labelWidth: 80,
                    name: 'abdkRisklevel'
                },
                {
                    xtype: 'displayfield',
                    x: 300,
                    y: 290,
                    id: 'abdkWarningtime',
                    fieldLabel: '预警时间',
                    labelWidth: 80,
                    name: 'abdkWarningtime'
                },
                {
                    xtype: 'label',
                    x: 10,
                    y: 320,
                    id:'abdkDocpath',
                    html: '<a href="'+record.data.abdkDocpath+'">文件下载</a>'
                },
                {
                    xtype: 'button',
                    handler: function(button, event) {
                        var form = this.up('form').getForm(); // get the basic form

                        if (form.isValid()) { // make sure the form contains valid data before submitting
                            form.submit({
                                url:'update_abdkts',

                                success: function(form, action) {

                                    Ext.Msg.alert('成功', '信息更新成功');
                                    var mystore = Ext.StoreMgr.get('abnmDkTransSupervisionStore'); //获得store对象
                                    mystore.load();

                                    win.close();
                                },
                                failure: function(form, action) {
                                    Ext.Msg.alert('失败', '信息更新失败');
                                }
                            });
                        } else { // display error alert if the data is invalid
                        Ext.Msg.alert('Invalid Data', 'Please correct form errors.');}
                    },
                    x: 90,
                    y: 560,
                    width: 90,
                    text: '确定'
                },
                {
                    xtype: 'button',
                    handler: function(button, event) {
                        win.close();
                    },
                    x: 240,
                    y: 560,
                    width: 90,
                    text: '取消'
                },
                {
                    xtype: 'gridpanel',
                    x: 10,
                    y: 350,
                    height: 200,
                    id: 'abnmIndexUpdateTab',
                    collapsible: false,
                    title: '预警参数设置',
                    forceFit: true,
                    store: getIndexStore,
                    columns: [
                    {
                        xtype: 'rownumberer',
                        width: 47,
                        text: '记录号'
                    },
                    {
                        xtype: 'gridcolumn',
                        dataIndex: 'abiClass',
                        text: '指标类别'
                    },
                    {
                        xtype: 'gridcolumn',
                        dataIndex: 'abiName',
                        text: '指标名称',
                        tooltip: ''
                    },
                    {
                        xtype: 'gridcolumn',
                        dataIndex: 'abiValue',
                        text: '指标值'
                    },
                    {
                        xtype: 'gridcolumn',
                        dataIndex: 'abiWeight',
                        text: '指标权重'
                    }
                    ],
                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                    }),
                    dockedItems: [
                    {
                        xtype: 'toolbar',
                        dock: 'top',
                        frame: false,
                        enableOverflow: true,
                        items: [
                        {
                            xtype: 'button',
                            handler: function(button, event) {




                                var indexUpdatePanel = Ext.widget("abnmIndexUpdateTab");
                                var indexWin = new Ext.Window({

                                    title: '增加指标',
                                    closable: true,
                                    layout: 'fit',
                                    jsonSubmit: true,
                                    items:[

                                    {
                                        xtype: 'form',
                                        id: 'indexAddForm',
                                        layout: {
                                            type: 'auto'
                                        },
                                        bodyPadding: 10,
                                        jsonSubmit: true,
                                        title: '',
                                        items: [
                                        {
                                            xtype: 'textfield',
                                            id: 'abiName',
                                            width: 340,
                                            fieldLabel: '指标名称',
                                            name: 'abiName'
                                        },{
                                            xtype: 'textfield',
                                            id: 'abiClass',
                                            width: 340,
                                            fieldLabel: '指标类别',
                                            name: 'abiClass'
                                        },{
                                            xtype: 'textfield',
                                            id: 'abiValue',
                                            width: 340,
                                            fieldLabel: '指标值',
                                            name: 'abiValue'
                                        },{
                                            xtype: 'textfield',
                                            id: 'abiWeight',
                                            width: 340,
                                            fieldLabel: '指标权重',
                                            name: 'abiWeight'
                                        },{
                                            xtype: 'textfield',
                                            id: 'dkId',
                                            width: 340,
                                            hidden:true,
                                            value:getDkId,
                                            fieldLabel: '所属地块ID',
                                            name: 'dkId'
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, event) {
                                                var myform = Ext.getCmp('indexAddForm').getForm();

                                                if (myform.isValid()) {
                                                    myform.submit({
                                                        url:'add_abi',

                                                        success: function(form, action) {
                                                            Ext.Msg.alert('成功', '增加选项成功');

                                                            getIndexStore.load({
                                                                params:{
                                                                    dkId:getDkId
                                                                }
                                                            });
                                                            indexWin.close();

                                                        },
                                                        failure: function(form, action) {
                                                            Ext.Msg.alert('失败', '增加选项失败');
                                                            indexWin.close();
                                                        }
                                                    });
                                                } else {
                                                    Ext.Msg.alert('注意', '填写信息不能为空，请检查！');
                                                }

                                                return;
                                            },
                                            text: '确定'
                                        }
                                        ]
                                    }



                                    ]
                                });
                                indexWin.show();





                            },
                            icon: 'images/file_view0.png',
                            text: '增加指标'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {



                                var grid = Ext.getCmp('abnmIndexUpdateTab');

                                var record = grid.getSelectionModel().getSelection();

                                if(record.length === 0){
                                    Ext.Msg.alert('提示','请先选择您要操作的行！');
                                    return;

                                }else{

                                    var  ids =new Array(record.length);
                                    for(var i = 0;i<record.length;i++){
                                        ids[i] = record[i].get("abiId");

                                    }
                                    //Ext.Msg.alert('提示',ids);



                                    Ext.Ajax.request({
                                        url:'delete_abiByIds',
                                        params:{ids:ids},
                                        success:function(response){
                                            Ext.Msg.alert('成功','删除成功');
                                            getIndexStore.load({
                                                params:{
                                                    dkId:getDkId
                                                }
                                            });
                                        },
                                        failure:function(response){
                                            Ext.Msg.alert('失败','删除失败');
                                        }

                                    });

                                }






                            },
                            icon: 'images/file_view0.png',
                            text: '删除指标'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {





                                var grid = Ext.getCmp('abnmIndexUpdateTab');

                                var record = grid.getSelectionModel().getSelection();

                                if(record.length != 1){
                                    Ext.Msg.alert('提示','请选定一条指标信息进行修改！');
                                    return;

                                }else{





                                    var indexUpdatePanel = Ext.widget("abnmIndexUpdateTab");
                                    var indexWin = new Ext.Window({

                                        title: '修改指标',
                                        closable: true,
                                        layout: 'fit',
                                        jsonSubmit: true,
                                        items:[

                                        {
                                            xtype: 'form',
                                            id: 'indexUpdateForm',
                                            layout: {
                                                type: 'auto'
                                            },
                                            bodyPadding: 10,
                                            jsonSubmit: true,
                                            title: '',
                                            items: [
                                            {
                                                xtype: 'textfield',
                                                id: 'abiId',
                                                width: 340,
                                                fieldLabel: '指标Id',
                                                hidder:true,
                                                value:record[0].get("abiId"),
                                                name: 'abiId'
                                            },
                                            {
                                                xtype: 'textfield',
                                                id: 'abiName',
                                                width: 340,
                                                fieldLabel: '指标名称',
                                                value:record[0].get("abiName"),
                                                name: 'abiName'
                                            },{
                                                xtype: 'textfield',
                                                id: 'abiClass',
                                                width: 340,
                                                fieldLabel: '指标类别',
                                                value:record[0].get("abiClass"),
                                                name: 'abiClass'
                                            },{
                                                xtype: 'textfield',
                                                id: 'abiValue',
                                                width: 340,
                                                fieldLabel: '指标值',
                                                value:record[0].get("abiValue"),
                                                name: 'abiValue'
                                            },{
                                                xtype: 'textfield',
                                                id: 'abiWeight',
                                                width: 340,
                                                fieldLabel: '指标权重',
                                                value:record[0].get("abiWeight"),
                                                name: 'abiWeight'
                                            },{
                                                xtype: 'textfield',
                                                id: 'dkId',
                                                width: 340,
                                                hidden:true,
                                                value:getDkId,
                                                fieldLabel: '所属地块ID',
                                                name: 'dkId'
                                            },
                                            {
                                                xtype: 'button',
                                                handler: function(button, event) {
                                                    var myform = Ext.getCmp('indexUpdateForm').getForm();

                                                    if (myform.isValid()) {
                                                        myform.submit({
                                                            url:'update_abi',

                                                            success: function(form, action) {
                                                                Ext.Msg.alert('成功', '修改指标成功');

                                                                getIndexStore.load({
                                                                    params:{
                                                                        dkId:getDkId
                                                                    }
                                                                });
                                                                indexWin.close();

                                                            },
                                                            failure: function(form, action) {
                                                                Ext.Msg.alert('失败', '修改指标失败');
                                                                indexWin.close();
                                                            }
                                                        });
                                                    } else {
                                                        Ext.Msg.alert('注意', '信息不能为空，请检查！');
                                                    }

                                                    return;
                                                },
                                                text: '确定'
                                            }
                                            ]
                                        }



                                        ]
                                    });
                                    indexWin.show();




                                }





                            },
                            icon: 'images/file_view0.png',
                            text: '修改指标'
                        }
                        ]
                    }
                    ]
                }
                ]
            }]
        });

        Ext.getCmp('abdkId').setValue(record.data.abdkId);
        Ext.getCmp('dkTbid').setValue(record.data.dkTbid);
        Ext.getCmp('abdkSeller').setValue(record.data.abdkSeller);
        Ext.getCmp('abdkBx').setValue(record.data.abdkBx);
        Ext.getCmp('abdkBprice').setValue(record.data.abdkBprice);
        Ext.getCmp('abdkAx').setValue(record.data.abdkAx);
        Ext.getCmp('dgcl').setValue(record.data.dgcl);
        Ext.getCmp('abdkAarea').setValue(record.data.abdkAarea);
        Ext.getCmp('dkArea').setValue(record.data.dkArea);
        Ext.getCmp('areaCode').setValue(record.data.areaCode);
        Ext.getCmp('projectId').setValue(record.data.projectId);
        Ext.getCmp('abdkSlope').setValue(record.data.abdkSlope);
        Ext.getCmp('abdkSlopevariance').setValue(record.data.abdkSlopevariance);
        Ext.getCmp('abdkBuyer').setValue(record.data.abdkBuyer);
        Ext.getCmp('abdkBy').setValue(record.data.abdkBy);
        Ext.getCmp('abdkAprice').setValue(record.data.abdkAprice);
        Ext.getCmp('abdkAy').setValue(record.data.abdkAy);
        Ext.getCmp('dgjj').setValue(record.data.dgjj);
        Ext.getCmp('abdkIsnormal').setValue(record.data.abdkIsnormal);
        Ext.getCmp('abdkRisklevel').setValue(record.data.abdkRisklevel);
        Ext.getCmp('abdkWarningtime').setValue(record.data.abdkWarningtime);



        win.show();


    }

});