/*
 * File: app/view/abnmWSRWUpdateTab.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.abnmWSRWUpdateTab', {
    extend: 'Ext.window.Window',
    alias: 'widget.abnmWSRWUpdateTab',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Display',
        'Ext.form.field.Date',
        'Ext.form.field.TextArea',
        'Ext.button.Button'
    ],

    id: 'abnmWSRWUpdateTab',
    width: 830,
    layout: 'fit',
    title: '全过程异常监管任务详细信息',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    height: 500,
                    id: 'abnmWSRWUpdateForm',
                    layout: 'absolute',
                    bodyPadding: 10,
                    jsonSubmit: true,
                    items: [
                        {
                            xtype: 'displayfield',
                            width: 780,
                            fieldLabel: '任务编号',
                            labelWidth: 80,
                            name: 'rwId'
                        },
                        {
                            xtype: 'displayfield',
                            x: 10,
                            y: 40,
                            width: 780,
                            fieldLabel: '项目名称',
                            labelWidth: 80,
                            name: 'projectName'
                        },
                        {
                            xtype: 'displayfield',
                            x: 10,
                            y: 70,
                            width: 780,
                            fieldLabel: '项目编号',
                            labelWidth: 80,
                            name: 'projectId'
                        },
                        {
                            xtype: 'displayfield',
                            x: 10,
                            y: 100,
                            width: 780,
                            fieldLabel: '任务类型',
                            labelWidth: 80,
                            name: 'rwClass'
                        },
                        {
                            xtype: 'datefield',
                            x: 10,
                            y: 180,
                            width: 780,
                            fieldLabel: '任务执行时间',
                            labelWidth: 80,
                            name: 'rwStarttime',
                            format: 'Y-m-d'
                        },
                        {
                            xtype: 'datefield',
                            x: 10,
                            y: 210,
                            width: 780,
                            fieldLabel: '任务截止时间',
                            labelWidth: 80,
                            name: 'rwEndtime',
                            format: 'Y-m-d'
                        },
                        {
                            xtype: 'textareafield',
                            x: 10,
                            y: 250,
                            height: 180,
                            width: 780,
                            fieldLabel: '任务描述',
                            labelWidth: 80,
                            name: 'rwContent'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                var form = this.up('form').getForm(); // get the basic form

                                if (form.isValid()) { // make sure the form contains valid data before submitting
                                    form.submit({
                                        url:'update_abwsRW',
                                        success: function(form, action) {

                                            Ext.Msg.alert('成功', '成功提交');
                                            var mystore = Ext.StoreMgr.get('abnmWholeSupervisionStore'); //获得store对象
                                            mystore.load();
                                            var mystore2 = Ext.StoreMgr.get('abnmWSRWstore'); //获得store对象
                                            mystore2.load();
                                            var win = Ext.getCmp('abnmWSRWUpdateTab');
                                            win.close();
                                        },
                                        failure: function(form, action) {
                                            Ext.Msg.alert('失败', '提交失败');
                                        }
                                    });
                                } else { // display error alert if the data is invalid
                                Ext.Msg.alert('Invalid Data', 'Please correct form errors.');}
                            },
                            x: 170,
                            y: 460,
                            width: 100,
                            text: '确定'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                var win = Ext.getCmp('abnmWSRWUpdateTab');
                                win.close();
                            },
                            x: 470,
                            y: 460,
                            width: 90,
                            text: '取消'
                        },
                        {
                            xtype: 'textfield',
                            x: 10,
                            y: 140,
                            width: 780,
                            fieldLabel: '任务下达人',
                            labelWidth: 80,
                            name: 'rwResponsiblePerson'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});