/*
 * File: app/view/aceeptApplyfile.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.aceeptApplyfile', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.aceeptApplyfile',

    requires: [
        'Ext.form.Panel',
        'Ext.button.Button',
        'Ext.form.field.File'
    ],

    id: 'aceeptApplyfile',
    layout: 'fit',
    title: '文件上传',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    height: 110,
                    id: 'applyForm1',
                    autoScroll: true,
                    layout: 'absolute',
                    bodyPadding: 10,
                    title: '',
                    jsonSubmit: true,
                    method: 'post',
                    url: 'submit_applyFile',
                    items: [
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                var f=Ext.getCmp('applyForm1');
                                var fkapplyfilename=Ext.getCmp('fkapplyfilename').getValue();
                                var fkapplyReport=Ext.getCmp('fkapplyReport').getValue();
                                var fkapplyFinancialDocuments=Ext.getCmp('fkapplyFinancialDocuments').getValue();
                                var fkapplyBidding=Ext.getCmp('fkapplyBidding').getValue();
                                var statusMap=Ext.getCmp('statusMap').getValue();
                                var planMap=Ext.getCmp('planMap').getValue();
                                var builtDrawingsMap=Ext.getCmp('builtDrawingsMap').getValue();
                                var tabs = this.up('tabpanel');

                                if(fkapplyfilename==''||fkapplyReport==''||fkapplyFinancialDocuments==''||fkapplyBidding==''||statusMap==''||planMap==''||builtDrawingsMap=='')
                                {
                                    Ext.MessageBox.alert('提示','请上传所有申请文件'+'0');
                                }
                                else
                                {
                                    Ext.MessageBox.confirm('提示','您确定要全部提交文件吗？',function(btn)
                                    {
                                        if(btn=='yes')
                                        {
                                            f.getForm().submit(
                                            {
                                                url:'submit_applyFile',
                                                method:'post',
                                                success:function(form, action){
                                                    tabs.removeAll(true);
                                                    var newtab = tabs.add(Ext.widget('acceptApply'));
                                                    Ext.getCmp('fileCheck').setValue('是');
                                                    Ext.MessageBox.alert('信息',action.result.msg);
                                                },
                                                failure:function(){

                                                    Ext.MessageBox.alert('错误','操作失败！');
                                                }
                                            }
                                            );

                                        }
                                    }
                                    );
                                }
                            },
                            x: 470,
                            y: 320,
                            text: '提交文件'
                        },
                        {
                            xtype: 'filefield',
                            x: 70,
                            y: 40,
                            id: 'fkapplyfilename',
                            fieldLabel: '上传复垦申请表(Word)',
                            labelWidth: 145,
                            name: 'fkapplyfilename',
                            buttonText: '选择文件'
                        },
                        {
                            xtype: 'filefield',
                            x: 70,
                            y: 100,
                            id: 'fkapplyReport',
                            fieldLabel: '上传验收自检报告(Word)',
                            labelWidth: 145,
                            name: 'fkapplyReport',
                            buttonText: '选择文件'
                        },
                        {
                            xtype: 'filefield',
                            x: 70,
                            y: 160,
                            id: 'fkapplyFinancialDocuments',
                            fieldLabel: '上传项目财务文件(Word)',
                            labelWidth: 145,
                            name: 'fkapplyFinancialDocuments',
                            buttonText: '选择文件'
                        },
                        {
                            xtype: 'filefield',
                            x: 70,
                            y: 220,
                            id: 'fkapplyBidding',
                            fieldLabel: '上传招投标文件(Word)',
                            labelWidth: 145,
                            name: 'fkapplyBidding',
                            buttonText: '选择文件'
                        },
                        {
                            xtype: 'filefield',
                            x: 560,
                            y: 40,
                            id: 'statusMap',
                            fieldLabel: '上传现状图(JPG)',
                            labelWidth: 120,
                            name: 'statusMap',
                            buttonText: '选择文件'
                        },
                        {
                            xtype: 'filefield',
                            x: 560,
                            y: 100,
                            id: 'planMap',
                            fieldLabel: '上传规划图(JPG)',
                            labelWidth: 120,
                            name: 'planMap',
                            buttonText: '选择文件'
                        },
                        {
                            xtype: 'filefield',
                            x: 560,
                            y: 160,
                            id: 'builtDrawingsMap',
                            fieldLabel: '上传竣工图(JPG)',
                            labelWidth: 120,
                            name: 'builtDrawingsMap',
                            buttonText: '选择文件'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});