/*
 * File: app/view/db_BackupRecoveryData.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.db_BackupRecoveryData', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.db_BackupRecoveryData',

    requires: [
        'Ext.form.Panel',
        'Ext.button.Button',
        'Ext.form.Label',
        'Ext.form.field.Checkbox',
        'Ext.form.field.File',
        'Ext.form.field.TextArea',
        'Ext.toolbar.Toolbar',
        'Ext.grid.Panel',
        'Ext.grid.RowNumberer',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.View',
        'Ext.selection.CheckboxModel'
    ],

    id: 'db_BackupRecoveryData',
    layout: 'border',
    title: '备份与恢复',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'panel',
                    dock: 'top',
                    height: 150,
                    width: 1177,
                    title: '备份数据库',
                    items: [
                        {
                            xtype: 'form',
                            margin: 0,
                            layout: {
                                type: 'hbox',
                                align: 'stretchmax'
                            },
                            items: [
                                {
                                    xtype: 'panel',
                                    width: 126,
                                    layout: 'fit',
                                    title: '',
                                    items: [
                                        {
                                            xtype: 'button',
                                            handler: function(button, event) {
                                                var description = Ext.getCmp("txt_backup_description").getValue( );

                                                Ext.Ajax.request(
                                                {
                                                    url : 'add_databseBackup',
                                                    params :
                                                    {
                                                        bkCommnet : description
                                                    },
                                                    success : function (response){
                                                        Ext.Msg.alert('成功提示', '数据库备份成功。');
                                                        //successResult();
                                                        var mystore = Ext.StoreMgr.get('dbBackupRecoveryStore');
                                                        mystore.load();
                                                    },
                                                    failure : function (response){
                                                        //failedResult();
                                                        Ext.Msg.alert('失败提示', '数据库备份失败，请重试。');
                                                    }
                                                });


                                                //Ext.MessageBox.show({
                                                //		    title : 'Please wait',
                                                //		    msg : 'Loading items...',
                                                //		    progressText : 'Initializing...',
                                                //		    width : 300,
                                                //		    progress : true,
                                                //		    closable : false,
                                                //		    animateTarget : 'mb6'
                                                //		});
                                                //
                                                //		// this hideous block creates the bogus progress
                                                //		var f = function (v)
                                                //		{
                                                //		    return function ()
                                                //		    {
                                                //		        if (v == 12)
                                                //		        {
                                                //		            Ext.MessageBox.hide();
                                                //		            Ext.example.msg('Done', 'Your fake items were loaded!');
                                                //		        }
                                                //		        else
                                                //		        {
                                                //		            var i = v / 11;
                                                //		            Ext.MessageBox.updateProgress(i, Math.round(100 * i) + '% completed');
                                                //		        }
                                                //		    };
                                                //		};
                                                //		for (var i = 1; i < 13; i++)
                                                //		{
                                                //		    setTimeout(f(i), i * 500);
                                                //		}
                                            },
                                            id: 'db_btn_StartBackup',
                                            text: '开始备份'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    flex: 1,
                                    height: 120,
                                    layout: 'absolute',
                                    title: '备份设置',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            x: 30,
                                            y: 5,
                                            fieldLabel: '备份频率',
                                            emptyText: '7'
                                        },
                                        {
                                            xtype: 'label',
                                            x: 270,
                                            y: 10,
                                            text: '天'
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            x: 310,
                                            y: 5,
                                            fieldLabel: '自动备份',
                                            boxLabel: '',
                                            checked: true
                                        },
                                        {
                                            xtype: 'filefield',
                                            x: 30,
                                            y: 30,
                                            width: 400,
                                            fieldLabel: '备份设置',
                                            emptyText: '202.112.95.210/DatabaseBackup/',
                                            buttonText: '浏览'
                                        },
                                        {
                                            xtype: 'textareafield',
                                            x: 30,
                                            y: 55,
                                            height: 40,
                                            id: 'txt_backup_description',
                                            width: 400,
                                            fieldLabel: '备注信息'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'panel',
                    flex: 1,
                    region: 'center',
                    layout: 'fit',
                    title: '恢复数据库',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    text: '恢复到此版本',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    text: '刷新'
                                },
                                {
                                    xtype: 'button',
                                    text: '删除'
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'gridpanel',
                            id: 'grid_db_backup',
                            store: 'dbBackupRecoveryStore',
                            columns: [
                                {
                                    xtype: 'rownumberer'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    dataIndex: 'version',
                                    text: '版本',
                                    format: '0.0'
                                },
                                {
                                    xtype: 'datecolumn',
                                    dataIndex: 'bkdate',
                                    text: '备份日期'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    dataIndex: 'size',
                                    text: '大小(kb)'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 200,
                                    defaultWidth: 200,
                                    dataIndex: 'description',
                                    text: '备注说明'
                                }
                            ],
                            selModel: Ext.create('Ext.selection.CheckboxModel', {

                            })
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        var grid = Ext.getCmp('grid_db_backup');
        var records =grid.getSelectionModel().getSelection();//获取到表上的那一列
        if(records.length > 1){
            Ext.MessageBox.show({
                title:"提示",
                msg:"只能选择一行数据",
                icon: Ext.MessageBox.INFO,
                buttons: Ext.Msg.OK
            });
            return;
        }else if(records.length < 1){
            Ext.MessageBox.show({
                title:"提示",
                msg:"请选择一个版本进行恢复。",
                icon: Ext.MessageBox.INFO,
                buttons: Ext.Msg.OK
            });
            return;
        }

        Ext.Msg.alert('成功提示', '数据库恢复成功。');
    }

});