/*
 * File: app/view/db_MapServerTab.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.db_MapServerTab', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.db_MapServerTab',

    requires: [
        'Ext.panel.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.form.Label',
        'Ext.button.Button'
    ],

    id: 'db_MapServerTab',
    layout: 'fit',
    title: '结果图',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    html: '<div id="mapdiv_mapServer" style="width:100%;height:100%;">',
                    width: 150,
                    listeners: {
                        afterrender: {
                            fn: me.onPanelAfterRender,
                            scope: me
                        }
                    },
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'label',
                                    text: '对比：'
                                },
                                {
                                    xtype: 'button',
                                    id: 'btn_MapServer_Swipe_image',
                                    text: '影像对比'
                                },
                                {
                                    xtype: 'button',
                                    id: 'btn_MapServer_Swipe_Map2',
                                    text: '历史数据'
                                },
                                {
                                    xtype: 'button',
                                    id: 'btn_MapServer_Swipe_Destroy',
                                    text: '清除对比'
                                },
                                {
                                    xtype: 'label',
                                    text: '定位：'
                                },
                                {
                                    xtype: 'button',
                                    id: 'btn_MapServer_Locate1',
                                    text: '项目1'
                                },
                                {
                                    xtype: 'button',
                                    id: 'btn_MapServer_Locate2',
                                    text: '项目2'
                                },
                                {
                                    xtype: 'label',
                                    text: '查询：'
                                },
                                {
                                    xtype: 'button',
                                    id: 'btn_MapServer_InfoQuery',
                                    text: '开始查询'
                                },
                                {
                                    xtype: 'button',
                                    id: 'btn_MapServer_InfoQueryDestroy',
                                    text: '结束查询'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onPanelAfterRender: function(component, eOpts) {
        var head = document.getElementsByTagName('head')[0];
        var script= document.createElement("script");
        script.type = "text/javascript";
        script.src="map/mapServer_map.js";
        head.appendChild(script);
    }

});