/*
 * File: app/view/EvaluateReport.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.EvaluateReport', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.EvaluateReport',

    requires: [
        'Ext.form.field.Text',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.grid.View',
        'Ext.toolbar.Paging',
        'Ext.selection.CheckboxModel'
    ],

    layout: 'fit',
    title: '项目验收评价结果',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'textfield',
                            id: 'EvaluateID',
                            fieldLabel: '项目编号'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                var mystore=Ext.StoreMgr.get('EvaluateReportStore');
                                mystore.load(
                                {params:{
                                    start:"0",
                                    limit:"25",
                                    searchKeyword:Ext.getCmp('EvaluateID').getValue()
                                }
                            }
                            );
                            },
                            icon: '',
                            text: '查询'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                var win=new Ext.Window({
                                    height: 250,
                                    width: 568,
                                    layout: {
                                        type: 'fit'
                                    },
                                    title: '文件上传',

                                    modal: true,
                                    items: [
                                    {
                                        xtype: 'form',
                                        height: 110,
                                        id: 'fileForm',
                                        autoScroll: true,
                                        layout: {
                                            type: 'absolute'
                                        },
                                        bodyPadding: 10,
                                        title: '',
                                        jsonSubmit: true,
                                        method: 'post',
                                        url: 'submit_applyFile',
                                        items: [
                                        {
                                            xtype: 'button',
                                            handler: function(button, event) {
                                                var excelName=Ext.getCmp('projectReportFile').getRawValue();
                                                var excelName1=Ext.getCmp('expertFile').getRawValue();
                                                var formPanel=Ext.getCmp('fileForm');
                                                if (excelName==""||excelName1==""){
                                                    Ext.Msg.show({title:'提示',msg:'请选择文件!',buttons:Ext.Msg.OK,icon:Ext.MessageBox.INFOR});
                                                    return;
                                                }else {
                                                    var array = new Array();
                                                    array = excelName.split("\\");
                                                    var length = array.length;
                                                    var fileName = "";
                                                    var index = 0;
                                                    for (index = 0; index < length; index++) {
                                                        if (fileName == "") {
                                                            fileName = array[index];
                                                        } else {
                                                            fileName = fileName + "/" + array[index];
                                                        }
                                                    }
                                                }

                                                formPanel.getForm().submit(
                                                {
                                                    url:'projectFileupload',
                                                    method:'post',
                                                    waitMsg:'数据上传中, 请稍等...',
                                                    success:function(form, action){
                                                        Ext.MessageBox.alert('信息',action.result.msg);
                                                    },
                                                    failure:function(){
                                                        Ext.MessageBox.alert("提示信息","请求失败,文件上传失败");
                                                    }
                                                }
                                                );
                                            },
                                            x: 230,
                                            y: 180,
                                            text: '上传文件'
                                        },
                                        {
                                            xtype: 'filefield',
                                            x: 70,
                                            y: 50,
                                            id: 'projectReportFile',
                                            fieldLabel: '竣工报告',
                                            labelWidth: 145,
                                            name: 'projectReportFile',
                                            buttonText: '浏览'
                                        },
                                        {
                                            xtype: 'filefield',
                                            x: 70,
                                            y: 115,
                                            id: 'expertFile',
                                            fieldLabel: '项目验收专家扫描件',
                                            labelWidth: 145,
                                            name: 'expertFile',
                                            buttonText: '浏览'
                                        }
                                        ]
                                    }
                                    ]
                                });

                                win.show();
                            },
                            icon: 'images/file_view0.png',
                            text: '上传验收文档'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                var win=new Ext.Window({
                                    height: 400,
                                    width: 620,
                                    title: '竣工报告',
                                    closable: true,
                                    layout: 'fit',
                                    jsonSubmit: true,
                                    items: [
                                    {
                                        xtype: 'form',
                                        height: 400,
                                        layout: {
                                            type: 'absolute'
                                        },
                                        bodyPadding: 10,
                                        title: '',
                                        items: [
                                        {
                                            xtype: 'image',
                                            x: 0,
                                            y: 0,
                                            height: 395,
                                            width: 615,
                                            src: 'images/jungong.jpg'
                                        }
                                        ]
                                    }
                                    ]
                                });
                                win.show();
                            },
                            icon: 'images/file_view0.png',
                            text: '竣工报告'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                var win=new Ext.Window({
                                    height: 620,
                                    width: 425,
                                    title: '专家意见扫描件',
                                    closable: true,
                                    layout: 'fit',
                                    jsonSubmit: true,
                                    items: [
                                    {
                                        xtype: 'form',
                                        height: 610,
                                        layout: {
                                            type: 'absolute'
                                        },
                                        bodyPadding: 10,
                                        title: '',
                                        items: [
                                        {
                                            xtype: 'image',
                                            x: 0,
                                            y: 0,
                                            height: 600,
                                            width: 410,
                                            src: 'images/expert.jpg'
                                        }
                                        ]
                                    }
                                    ]
                                });
                                win.show();
                            },
                            icon: 'images/file_view0.png',
                            text: '专家意见扫描件'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                var tabs = this.up('tabpanel');
                                tabs.removeAll(true);
                                var newtab = tabs.add(Ext.widget('manageProject'));
                            },
                            icon: 'images/return.png',
                            text: '返回到项目管理'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'gridpanel',
                    id: 'EvaluateReportGrid',
                    title: '',
                    store: 'EvaluateReportStore',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'projectId',
                            text: '项目编号'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'projectname',
                            text: '项目名称'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 130,
                            dataIndex: 'soilAuditOpinion',
                            text: '土壤质量审核意见'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 130,
                            dataIndex: 'gongResults',
                            text: '工程质量验收结果'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 150,
                            dataIndex: 'expertResults',
                            text: '专家综合评价结果'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'soilQualityGrade',
                            text: '土壤质量结果'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 140,
                            dataIndex: 'soilQualityComment',
                            text: '土壤质量备注说明'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'gongCqgc',
                            text: '拆迁工程质量'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 130,
                            dataIndex: 'gongNtsl',
                            text: '农田水利工程质量'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 130,
                            dataIndex: 'gongTdpz',
                            text: '土地平整工程质量'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 130,
                            dataIndex: 'gongTjdl',
                            text: '田间道路工程质量'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 120,
                            dataIndex: 'microreliefDescription',
                            text: '专家微地貌描述'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 150,
                            dataIndex: 'trafficConditions',
                            text: '项目交通条件专家意见'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 150,
                            dataIndex: 'goukanQuality',
                            text: '沟粪函坎质量专家意见'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 100,
                            dataIndex: 'landProportion',
                            text: '田土比重'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 100,
                            dataIndex: 'waterStorageCapacity',
                            text: '蓄水能力'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 150,
                            dataIndex: 'fertilityEvaluation',
                            text: '土壤肥力专家意见'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 150,
                            dataIndex: 'formingClodsDegree',
                            text: '主体田块成型度'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 150,
                            dataIndex: 'expert',
                            text: '专家姓名与单位'
                        }
                    ],
                    viewConfig: {
                        id: 'EvaluateReportView'
                    },
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'EvaluateReportStore'
                        }
                    ],
                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                    })
                }
            ]
        });

        me.callParent(arguments);
    }

});