/*
 * File: app/view/gongchengdataAdd.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.gongchengdataAdd', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.gongchengdataAdd',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.TextArea',
        'Ext.button.Button'
    ],

    layout: 'fit',
    title: '添加项目工程质量信息',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    height: 110,
                    id: 'gongchengdataAddForm',
                    autoScroll: true,
                    layout: 'absolute',
                    bodyPadding: 10,
                    title: '',
                    jsonSubmit: true,
                    standardSubmit: false,
                    url: 'add_gongchengxinxi',
                    items: [
                        {
                            xtype: 'textfield',
                            x: 40,
                            y: 90,
                            width: 370,
                            fieldLabel: '项目实际规模(公顷)',
                            labelWidth: 160,
                            name: 'area',
                            emptyText: '3.1116'
                        },
                        {
                            xtype: 'textfield',
                            x: 490,
                            y: 90,
                            width: 420,
                            fieldLabel: '采集人',
                            name: 'recorder',
                            emptyText: '马全胜'
                        },
                        {
                            xtype: 'textfield',
                            x: 40,
                            y: 40,
                            width: 370,
                            fieldLabel: '项目编号',
                            name: 'projectId',
                            emptyText: 'FK001'
                        },
                        {
                            xtype: 'textfield',
                            x: 40,
                            y: 350,
                            hidden: true,
                            width: 310,
                            fieldLabel: '现场图片',
                            name: 'fkPicture',
                            value: 'Upload/before/zjd.jpg'
                        },
                        {
                            xtype: 'textfield',
                            x: 490,
                            y: 40,
                            width: 420,
                            fieldLabel: '项目名称',
                            name: 'projectName',
                            emptyText: '长寿区新市镇新合村等(2)个村农村集体建设用地复垦项目'
                        },
                        {
                            xtype: 'textareafield',
                            x: 40,
                            y: 140,
                            height: 82,
                            width: 370,
                            fieldLabel: '拆迁工程完成质量',
                            name: 'chgc',
                            emptyText: '拆除砖木结构房屋4843m2，砖混结构房屋1778 m2，土墙结构房屋1046m2，砖石结构房屋76m2，穿逗结构房屋917m2，简易结构房屋306m2，完成全部拆除工程任务。'
                        },
                        {
                            xtype: 'textareafield',
                            x: 40,
                            y: 240,
                            height: 82,
                            width: 370,
                            fieldLabel: '土地平整工程完成质量',
                            name: 'tdpz',
                            emptyText: '复垦后耕地的有效土层厚度不低于0.40m；复垦后水平梯地相同台面内的田块坡度不超过5°；复垦后耕地耕作层的砾石含量＜5%；复垦后耕地耕作层的侵入物含量＜5%，达到土地平整工程设计要求。'
                        },
                        {
                            xtype: 'textareafield',
                            x: 490,
                            y: 240,
                            height: 82,
                            width: 420,
                            fieldLabel: '田间道路工程完成质量',
                            name: 'tjdl',
                            emptyText: '生产路设计路面宽度为0.8m，材质为水泥和条石，水泥路面采用C20砼现浇成型，路面厚度为0.10m，工程质量达标。'
                        },
                        {
                            xtype: 'textareafield',
                            x: 490,
                            y: 140,
                            height: 82,
                            width: 420,
                            fieldLabel: '农田水利工程完成质量',
                            name: 'ntsl',
                            emptyText: '（1）项目区规划新修和现有灌溉渠整修按75%的灌溉保证率进行设计；（2）维修和新修排水沟：采用矩形断面，浆砌条石或浆砌砖砖结构，新修砖排水沟规格为0.3×0.4m（宽×深）；'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                var form = this.up('form').getForm(); // get the basic form
                                if (form.isValid()) { // make sure the form contains valid data before submitting
                                    form.submit({
                                        success: function(form, action) {
                                            Ext.Msg.alert('Success', action.result.msg);
                                        },
                                        failure: function(form, action) {
                                            Ext.Msg.alert('Failed', action.result.msg);
                                        }
                                    });
                                } else { // display error alert if the data is invalid
                                    Ext.Msg.alert('Invalid Data', 'Please correct form errors.');
                                }
                            },
                            x: 360,
                            y: 360,
                            icon: 'images/table_save.png ',
                            text: '保存'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                var tabs = this.up('tabpanel');
                                tabs.removeAll(true);
                                //用tabs.add()新增加一个tab页面,通过Ext.widget(xtype)得到文章回收站的页面
                                var newtab = tabs.add(Ext.widget('GongchengDataManage'));
                            },
                            x: 490,
                            y: 360,
                            icon: 'images/return.png',
                            text: '返回',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {

    }

});