/*
 * File: app/view/infoReportTab.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.infoReportTab', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.infoReportTab',

    requires: [
        'Ext.form.Panel',
        'Ext.grid.Panel',
        'Ext.grid.RowNumberer',
        'Ext.grid.column.Date',
        'Ext.grid.View',
        'Ext.selection.CheckboxModel',
        'Ext.form.field.Date',
        'Ext.button.Button',
        'Ext.toolbar.Paging'
    ],

    id: 'infoReportTab',
    layout: 'fit',
    title: '监管>>违规流转投诉举报',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    height: 421,
                    autoScroll: true,
                    layout: 'border',
                    bodyPadding: 10,
                    jsonSubmit: true,
                    items: [
                        {
                            xtype: 'gridpanel',
                            region: 'center',
                            collapsible: false,
                            title: '',
                            forceFit: true,
                            store: 'InfoReportStore',
                            columns: [
                                {
                                    xtype: 'rownumberer',
                                    width: 39
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'reportTitle',
                                    text: '来信主题'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'reporterName',
                                    text: '来信人'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'reportClass',
                                    text: '类别'
                                },
                                {
                                    xtype: 'datecolumn',
                                    dataIndex: 'reportTime',
                                    text: '来信时间',
                                    format: 'Y-m-d'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'reportIsreply',
                                    text: '是否回复'
                                },
                                {
                                    xtype: 'datecolumn',
                                    dataIndex: 'reportReplytime',
                                    text: '回复时间',
                                    format: 'Y-m-d'
                                }
                            ],
                            selModel: Ext.create('Ext.selection.CheckboxModel', {

                            }),
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    frame: false,
                                    enableOverflow: true,
                                    items: [
                                        {
                                            xtype: 'datefield',
                                            id: 'searchDateReport',
                                            width: 204,
                                            fieldLabel: '起始时间',
                                            labelWidth: 70,
                                            format: 'Y-m-d'
                                        },
                                        {
                                            xtype: 'textfield',
                                            id: 'searchKeywordReport',
                                            width: 211,
                                            fieldLabel: '',
                                            labelWidth: 80,
                                            emptyText: '请输入搜索关键字'
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, event) {
                                                var getDate = Ext.util.Format.date(Ext.getCmp('searchDateReport').getValue(),'Y-m-d');
                                                var getKeyword = Ext.getCmp('searchKeywordReport').getValue();
                                                var mystore=Ext.StoreMgr.get('InfoReportStore'); //获得store对象
                                                //在load事件中添加参数
                                                //mystore.load(
                                                //{params:{
                                                //    start:"0",
                                                //    limit:"25",
                                                //    searchKeyword:getKeyword,
                                                //    searchDate:getDate
                                                //}
                                                //}
                                                //);



                                                mystore.on('beforeload',function(store,options){

                                                    var new_params = {
                                                        searchKeyword:getKeyword,
                                                        searchDate:getDate
                                                    };

                                                    Ext.apply(store.proxy.extraParams,new_params);
                                                });

                                                mystore.load(
                                                {
                                                    params:{
                                                        start:"0",
                                                        limit:"25"
                                                    }
                                                }
                                                );
                                            },
                                            icon: 'images/file_view0.png',
                                            text: '搜索'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'pagingtoolbar',
                                    dock: 'bottom',
                                    height: 36,
                                    width: 360,
                                    displayInfo: true,
                                    store: 'InfoReportStore'
                                }
                            ],
                            listeners: {
                                cellclick: {
                                    fn: me.onGridpanelCellClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onGridpanelCellClick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {
        if(cellIndex === undefined || cellIndex < 2) return;




        var win = new Ext.Window({

            title:'来信详细信息',
            closable:true,
            layout:'fit',
            items:[
            {
                xtype: 'form',
                height: 600,
                layout: {
                    type: 'absolute'
                },
                bodyPadding: 10,
                jsonSubmit: true,
                items: [
                {
                    xtype: 'displayfield',
                    x: 10,
                    y: 10,
                    width: 230,
                    fieldLabel: '姓名',
                    id: 'reporterName',
                    name: 'reporterName'
                },
                {
                    xtype: 'displayfield',
                    x: 10,
                    y: 10,
                    hidden: true,
                    width: 230,
                    fieldLabel: '是否回复',
                    id: 'reportIsreply',
                    name: 'reportIsreply'
                },
                {
                    xtype: 'displayfield',
                    x: 10,
                    y: 10,
                    hidden: true,
                    width: 230,
                    fieldLabel: '来信ID',
                    id: 'reportId',
                    name: 'reportId'
                },
                {

                    xtype: 'displayfield',
                    x: 10,
                    y: 10,
                    hidden: true,
                    width: 230,
                    fieldLabel: '附件',
                    id: 'reportedAttachment',
                    name: 'reportedAttachment'

                },
                {
                    xtype: 'displayfield',
                    x: 540,
                    y: 40,
                    width: 230,
                    fieldLabel: '联系电话',
                    id: 'reporterTel',
                    name: 'reporterTel'
                },
                {
                    xtype: 'displayfield',
                    x: 10,
                    y: 40,
                    width: 230,
                    fieldLabel: '联系地址',
                    id: 'reporterAddress',
                    name: 'reporterAddress'
                },
                {
                    xtype: 'displayfield',
                    x: 10,
                    y: 70,
                    width: 230,
                    fieldLabel: '问题发生地',
                    id: 'reportedPlace',
                    name: 'reportedPlace'
                },
                {
                    xtype: 'displayfield',
                    x: 10,
                    y: 100,
                    width: 230,
                    fieldLabel: '被反映单位（人）',
                    id: 'reportedName',
                    name: 'reportedName'
                },
                {
                    xtype: 'displayfield',
                    x: 10,
                    y: 130,
                    width: 230,
                    fieldLabel: '投诉举报类别',
                    id: 'reportClass',
                    name: 'reportClass'
                },
                {
                    xtype: 'displayfield',
                    x: 270,
                    y: 130,
                    width: 230,
                    fieldLabel: '来信时间',
                    id: 'reportTime',
                    name: 'reportTime'
                },
                {
                    xtype: 'displayfield',
                    x: 540,
                    y: 130,
                    hidden: true,
                    width: 230,
                    fieldLabel: '回复时间',
                    id: 'reportReplytime',
                    name: 'reportReplytime'
                },
                {
                    xtype: 'displayfield',
                    x: 10,
                    y: 360,
                    width: 230,
                    fieldLabel: '回复人',
                    id: 'reportReplyer',
                    name: 'reportReplyer'
                },
                {
                    xtype: 'displayfield',
                    x: 270,
                    y: 100,
                    width: 230,
                    fieldLabel: '被反映人单位',
                    id: 'reportedDepartname',
                    name: 'reportedDepartname'
                },
                {
                    xtype: 'displayfield',
                    x: 10,
                    y: 160,
                    width: 770,
                    fieldLabel: '信件主题',
                    id: 'reportTitle',
                    name: 'reportTitle'
                },
                {
                    xtype: 'displayfield',
                    x: 270,
                    y: 70,
                    width: 230,
                    fieldLabel: '问题发生时间',
                    id: 'reportedTime',
                    name: 'reportedTime'
                },
                {
                    xtype: 'displayfield',
                    x: 540,
                    y: 70,
                    width: 230,
                    fieldLabel: '被反映单位级别',
                    id: 'reportedDepartlevel',
                    name: 'reportedDepartlevel'
                },
                {
                    xtype: 'displayfield',
                    x: 540,
                    y: 10,
                    width: 230,
                    fieldLabel: '身份证号',
                    id: 'reporterIdnum',
                    name: 'reporterIdnum'
                },
                {
                    xtype: 'displayfield',
                    x: 270,
                    y: 40,
                    width: 230,
                    fieldLabel: '邮政编码',
                    id: 'reporterZipcode',
                    name: 'reporterZipcode'
                },
                {
                    xtype: 'displayfield',
                    x: 270,
                    y: 10,
                    width: 230,
                    fieldLabel: '电子邮件',
                    id: 'reporterEmail',
                    name: 'reporterEmail'
                },
                {
                    xtype: 'displayfield',
                    x: 10,
                    y: 200,
                    height: 150,
                    width: 770,
                    fieldLabel: '来信内容（至少40个字）',
                    id: 'reportContent',
                    name: 'reportContent'
                },
                {
                    xtype: 'textareafield',
                    x: 10,
                    y: 390,
                    height: 150,
                    width: 770,
                    fieldLabel: '回复内容',
                    id: 'reportReplycontent',
                    name: 'reportReplycontent'
                },
                {
                    xtype: 'button',
                    handler: function(button, event) {
                        var form = this.up('form').getForm(); // get the basic form


                        if (form.isValid()) { // make sure the form contains valid data before submitting
                            form.submit({
                                url:'update_infoReport',

                                success: function(form, action) {

                                    Ext.Msg.alert('成功', '成功回复');
                                    var mystore = Ext.StoreMgr.get('InfoReportStore'); //获得store对象
                                    mystore.load();

                                    win.close();
                                },
                                failure: function(form, action) {
                                    Ext.Msg.alert('失败', '回复失败');
                                }
                            });
                        } else { // display error alert if the data is invalid
                        Ext.Msg.alert('Invalid Data', 'Please correct form errors.');}
                    },
                    x: 90,
                    y: 550,
                    text: '确定并发送邮件'
                },
                {
                    xtype: 'button',
                    handler: function(button, event) {
                        win.close();
                    },
                    x: 260,
                    y: 550,
                    width: 90,
                    text: '取消'
                }
                ]
            }

            ]

        });


        Ext.getCmp('reportTime').setValue(record.data.reportTime);
        Ext.getCmp('reportId').setValue(record.data.reportId);
        Ext.getCmp('reportClass').setValue(record.data.reportClass);
        Ext.getCmp('reportTitle').setValue(record.data.reportTitle);
        Ext.getCmp('reportContent').setValue(record.data.reportContent);
        Ext.getCmp('reporterName').setValue(record.data.reporterName);
        Ext.getCmp('reporterEmail').setValue(record.data.reporterEmail);
        Ext.getCmp('reporterAddress').setValue(record.data.reporterAddress);
        Ext.getCmp('reporterZipcode').setValue(record.data.reporterZipcode);
        Ext.getCmp('reporterTel').setValue(record.data.reporterTel);
        Ext.getCmp('reporterIdnum').setValue(record.data.reporterIdnum);
        Ext.getCmp('reportedPlace').setValue(record.data.reportedPlace);
        Ext.getCmp('reportedTime').setValue(record.data.reportedTime);
        Ext.getCmp('reportedDepartlevel').setValue(record.data.reportedDepartlevel);
        Ext.getCmp('reportedDepartname').setValue(record.data.reportedDepartname);
        Ext.getCmp('reportedName').setValue(record.data.reportedName);
        Ext.getCmp('reportReplytime').setValue(record.data.reportReplytime);
        Ext.getCmp('reportedAttachment').setValue(record.data.reportedAttachment);
        Ext.getCmp('reportReplyer').setValue(record.data.reportReplyer);
        Ext.getCmp('reportIsreply').setValue(record.data.reportIsreply);
        Ext.getCmp('reportReplycontent').setValue(record.data.reportReplycontent);






        win.show();
    }

});