/*
 * File: app/view/infoVoteTab.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.infoVoteTab', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.infoVoteTab',

    requires: [
        'Ext.form.Panel',
        'Ext.grid.Panel',
        'Ext.grid.RowNumberer',
        'Ext.grid.column.Date',
        'Ext.grid.View',
        'Ext.form.field.Text',
        'Ext.button.Button',
        'Ext.toolbar.Paging',
        'Ext.selection.CheckboxModel'
    ],

    id: 'infoVoteTab',
    layout: 'fit',
    title: '监管>>网上投票',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    id: 'infoVoteForm',
                    layout: 'border',
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'gridpanel',
                            region: 'center',
                            id: 'infoVoteGrid',
                            title: '',
                            forceFit: true,
                            store: 'InfoVoteStore',
                            columns: [
                                {
                                    xtype: 'rownumberer'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'voteTitle',
                                    text: '主题'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'voteVoter',
                                    text: '发起人'
                                },
                                {
                                    xtype: 'datecolumn',
                                    dataIndex: 'voteStarttime',
                                    text: '开始时间',
                                    format: 'Y-m-d'
                                },
                                {
                                    xtype: 'datecolumn',
                                    dataIndex: 'voteEndtime',
                                    text: '结束时间',
                                    format: 'Y-m-d'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'voteState',
                                    text: '状态'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'voteClass',
                                    text: '投票类型'
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    enableOverflow: true,
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            id: 'searchKeywordVote',
                                            width: 173,
                                            fieldLabel: '',
                                            emptyText: '请输入搜索关键字'
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, event) {

                                                var getKeyword = Ext.getCmp('searchKeywordVote').getValue();
                                                var mystore=Ext.StoreMgr.get('InfoVoteStore'); //获得store对象


                                                //在load事件中添加参数
                                                //mystore.load(
                                                //{params:{
                                                //    start:"0",
                                                //    limit:"25",
                                                //    searchKeyword:getKeyword
                                                //}
                                                //}
                                                //);



                                                mystore.on('beforeload',function(store,options){

                                                    var new_params = {
                                                        searchKeyword:getKeyword
                                                    };

                                                    Ext.apply(store.proxy.extraParams,new_params);
                                                });

                                                mystore.load(
                                                {
                                                    params:{
                                                        start:"0",
                                                        limit:"25"
                                                    }
                                                }
                                                );
                                            },
                                            icon: 'images/file_view0.png',
                                            text: '搜索'
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, event) {
                                                //var newPanel = Ext.widget("infoVotePublishTab");

                                                var getVoteoptionAddstore = Ext.StoreMgr.get('InfoVoteoptionAddStore');//获得store对象
                                                getVoteoptionAddstore.load({
                                                    params:{voteId:0}
                                                });
                                                var win = new Ext.Window({

                                                    title: '新建投票',
                                                    closable: true,
                                                    layout: 'fit',
                                                    jsonSubmit: true,
                                                    items:[


                                                    {
                                                        xtype: 'form',
                                                        id: 'infoVotePublishForm',
                                                        layout: {
                                                            type: 'absolute'
                                                        },
                                                        bodyPadding: 10,
                                                        title: '',
                                                        jsonSubmit: true,
                                                        items: [
                                                        {
                                                            xtype: 'textfield',
                                                            x: 40,
                                                            y: 10,
                                                            width: 690,
                                                            fieldLabel: '投票主题',
                                                            name: 'voteTitle'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            x: 40,
                                                            y: 40,
                                                            height: 100,
                                                            width: 690,
                                                            fieldLabel: '投票简介',
                                                            name: 'voteIntroduction'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            x: 40,
                                                            y: 150,
                                                            width: 690,
                                                            fieldLabel: '发起人',
                                                            name: 'voteVoter'
                                                        },
                                                        {
                                                            xtype: 'radiogroup',
                                                            x: 40,
                                                            y: 180,
                                                            width: 320,
                                                            fieldLabel: '投票类型',
                                                            items: [
                                                            {
                                                                xtype: 'radiofield',
                                                                name: 'voteClass',
                                                                boxLabel: '单选',
                                                                inputValue: '单选'
                                                            },
                                                            {
                                                                xtype: 'radiofield',
                                                                name: 'voteClass',
                                                                boxLabel: '多选',
                                                                inputValue: '多选'
                                                            }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'datefield',
                                                            x: 410,
                                                            y: 180,
                                                            width: 260,
                                                            fieldLabel: '结束时间',
                                                            name: 'voteEndtime',
                                                            format: 'Y-m-d'
                                                        },
                                                        {
                                                            xtype: 'gridpanel',
                                                            x: 140,
                                                            y: 210,
                                                            height: 319,
                                                            id: 'infoVoteoptionGrid',
                                                            width: 590,
                                                            title: '',
                                                            store: getVoteoptionAddstore,
                                                            columns: [
                                                            {
                                                                xtype: 'rownumberer'
                                                            },
                                                            {
                                                                xtype: 'gridcolumn',
                                                                dataIndex: 'voptionContent',
                                                                text: '选项内容'
                                                            }
                                                            ],
                                                            dockedItems: [
                                                            {
                                                                xtype: 'toolbar',
                                                                dock: 'top',
                                                                items: [
                                                                {
                                                                    xtype: 'button',
                                                                    handler: function(button, event) {
                                                                        //var voptionPanel = Ext.widget("infoVoteoptionShowTab");
                                                                        var voptionwin = new Ext.Window({

                                                                            title: '增加选项',
                                                                            closable: true,
                                                                            layout: 'fit',
                                                                            jsonSubmit: true,
                                                                            items:[

                                                                            {
                                                                                xtype: 'form',
                                                                                id: 'voptionForm',
                                                                                layout: {
                                                                                    type: 'auto'
                                                                                },
                                                                                bodyPadding: 10,
                                                                                jsonSubmit: true,
                                                                                title: '',
                                                                                items: [
                                                                                {
                                                                                    xtype: 'textfield',
                                                                                    id: 'voptionContent',
                                                                                    width: 340,
                                                                                    fieldLabel: '投票选项',
                                                                                    name: 'voptionContent'
                                                                                },
                                                                                {
                                                                                    xtype: 'button',
                                                                                    handler: function(button, event) {
                                                                                        var myform = Ext.getCmp('voptionForm').getForm();

                                                                                        if (myform.isValid()) {
                                                                                            myform.submit({
                                                                                                url:'add_voteoption',
                                                                                                success: function(form, action) {
                                                                                                    Ext.Msg.alert('成功', '增加选项成功');

                                                                                                    getVoteoptionAddstore.load();
                                                                                                    voptionwin.close();

                                                                                                },
                                                                                                failure: function(form, action) {
                                                                                                    Ext.Msg.alert('失败', '修改内容失败');
                                                                                                    voptionwin.close();
                                                                                                }
                                                                                            });
                                                                                        } else {
                                                                                            Ext.Msg.alert('注意', '填写信息不能为空，请检查！');
                                                                                        }

                                                                                        return;
                                                                                    },
                                                                                    text: '确定'
                                                                                }
                                                                                ]
                                                                            }



                                                                            ]
                                                                        });
                                                                        voptionwin.show();
                                                                    },
                                                                    text: '增加选项'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    handler: function(button, event) {
                                                                        var grid = Ext.getCmp('infoVoteoptionGrid');

                                                                        var record = grid.getSelectionModel().getSelection();

                                                                        if(record.length === 0){
                                                                            Ext.Msg.alert('提示','请先选择您要操作的行！');
                                                                            return;

                                                                        }else{


                                                                            var  voptionIds =new Array(record.length);
                                                                            for(var i = 0;i<record.length;i++){
                                                                                voptionIds[i] = record[i].get("voptionId");

                                                                            }


                                                                            Ext.Ajax.request({
                                                                                url:'del_voptionIds',
                                                                                params:{voptionIds:voptionIds},

                                                                                success:function(response){
                                                                                    Ext.Msg.alert('成功','删除成功');
                                                                                    var mystore = Ext.StoreMgr.get('InfoVoteoptionAddStore');
                                                                                    mystore.load();

                                                                                }

                                                                            });

                                                                        }
                                                                    },
                                                                    text: '删除选项'
                                                                }
                                                                ]
                                                            }
                                                            ],
                                                            selModel: Ext.create('Ext.selection.CheckboxModel', {

                                                            })
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            handler: function(button, event) {
                                                                var myform = Ext.getCmp('infoVotePublishForm').getForm();

                                                                if (myform.isValid()) {
                                                                    myform.submit({
                                                                        url:'add_vote',
                                                                        success: function(form, action) {
                                                                            Ext.Msg.alert('成功', '投票新建成功');

                                                                            var mystore = Ext.StoreMgr.get('InfoVoteStore'); //获得store对象

                                                                            mystore.load();
                                                                            win.close();


                                                                        },
                                                                        failure: function(form, action) {
                                                                            Ext.Msg.alert('失败', '修改内容失败');

                                                                        }
                                                                    });
                                                                } else {
                                                                    Ext.Msg.alert('注意', '填写信息不能为空，请检查！');
                                                                }

                                                                return;
                                                            },
                                                            x: 170,
                                                            y: 540,
                                                            text: '确定发起投票'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            x: 380,
                                                            y: 540,
                                                            width: 80,
                                                            text: '重置'
                                                        }
                                                        ]
                                                    }




                                                    ]
                                                });
                                                win.show();
                                            },
                                            icon: 'images/table_add.png',
                                            text: '新建投票'
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, event) {
                                                var grid = Ext.getCmp('infoVoteGrid');
                                                var record = grid.getSelectionModel().getSelection();

                                                if(record.length != 1 || record[0].get("voteState")!= '待发布'){
                                                    Ext.Msg.alert('提示','请选择一个待发布的投票！');
                                                    return;

                                                }else{


                                                    Ext.Ajax.request({
                                                        url:'update_voteStateTo2',
                                                        params:{voteIds:record[0].get("voteId")},

                                                        success:function(response){
                                                            Ext.Msg.alert('成功','投票开始');
                                                            var mystore = Ext.StoreMgr.get('InfoVoteStore');
                                                            mystore.load();

                                                        }

                                                    });
                                                }

                                            },
                                            icon: 'images/table_add.png',
                                            text: '启动投票'
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, event) {
                                                var grid = Ext.getCmp('infoVoteGrid');
                                                var record = grid.getSelectionModel().getSelection();

                                                if(record.length != 1 || record[0].get("voteState")!= '正在进行'){
                                                    Ext.Msg.alert('提示','请选择一个正在进行的投票！');
                                                    return;

                                                }else{


                                                    Ext.Ajax.request({
                                                        url:'update_voteStateTo3',
                                                        params:{voteIds:record[0].get("voteId")},

                                                        success:function(response){
                                                            Ext.Msg.alert('成功','投票已停止');
                                                            var mystore = Ext.StoreMgr.get('InfoVoteStore');
                                                            mystore.load();

                                                        }

                                                    });
                                                }

                                            },
                                            icon: 'images/table_add.png',
                                            text: '停止投票'
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, event) {
                                                var grid = Ext.getCmp('infoVoteGrid');

                                                var record = grid.getSelectionModel().getSelection();




                                                if(record.length != 1||record[0].get("voteState") == '正在进行'){
                                                    Ext.Msg.alert('提示','请选择一条未发布或已停止的投票');
                                                    return;

                                                }else{

                                                    var getVoteId = record[0].data.voteId;
                                                    var voteOptionStore = Ext.StoreMgr.get('InfoVoteoptionUpdateStore');
                                                    voteOptionStore.load(
                                                    {
                                                        params:{voteId:getVoteId}
                                                    }
                                                    );
                                                    //var newPanel = Ext.widget("infoVoteUpdateTab");
                                                    //Ext.Msg.alert('提示',record[0].data.voteId);

                                                    var win = new Ext.Window({

                                                        title: '修改投票',
                                                        closable: true,
                                                        layout: 'fit',
                                                        jsonSubmit: true,
                                                        params:{voteId:record[0].data.voteId},
                                                        items:[

                                                        {
                                                            xtype: 'form',
                                                            id: 'infoVoteUpdateForm',
                                                            layout: {
                                                                type: 'absolute'
                                                            },
                                                            bodyPadding: 10,
                                                            title: '',
                                                            baseParams: {
                                                                voteId: ''
                                                            },
                                                            jsonSubmit: true,
                                                            items: [
                                                            {
                                                                xtype: 'textfield',
                                                                x: 40,
                                                                y: 10,
                                                                width: 690,
                                                                hidden: true,
                                                                fieldLabel: '投票Id',
                                                                id: 'voteId',
                                                                name: 'voteId'
                                                            },
                                                            {
                                                                xtype: 'textfield',
                                                                x: 40,
                                                                y: 10,
                                                                width: 690,
                                                                fieldLabel: '投票主题',
                                                                id: 'voteTitle',
                                                                name: 'voteTitle'
                                                            },
                                                            {
                                                                xtype: 'textfield',
                                                                x: 40,
                                                                y: 40,
                                                                height: 100,
                                                                width: 690,
                                                                fieldLabel: '投票简介',
                                                                id: 'voteIntroduction',
                                                                name: 'voteIntroduction'
                                                            },
                                                            {
                                                                xtype: 'textfield',
                                                                x: 40,
                                                                y: 150,
                                                                width: 690,
                                                                fieldLabel: '发起人',
                                                                id: 'voteVoter',
                                                                name: 'voteVoter'
                                                            },
                                                            {
                                                                xtype: 'radiogroup',
                                                                x: 40,
                                                                y: 180,
                                                                width: 210,
                                                                fieldLabel: '投票类型',
                                                                id: 'voteClass',
                                                                items: [
                                                                {
                                                                    xtype: 'radiofield',
                                                                    name: 'voteClass',
                                                                    boxLabel: '单选',
                                                                    inputValue: '单选'
                                                                },
                                                                {
                                                                    xtype: 'radiofield',
                                                                    name: 'voteClass',
                                                                    boxLabel: '多选',
                                                                    inputValue: '多选'
                                                                }
                                                                ]
                                                            },
                                                            {
                                                                xtype: 'displayfield',
                                                                x: 270,
                                                                y: 180,
                                                                width: 220,
                                                                fieldLabel: '开始时间',
                                                                id: 'voteStarttime',
                                                                name: 'voteStarttime'
                                                            },
                                                            {
                                                                xtype: 'datefield',
                                                                x: 500,
                                                                y: 180,
                                                                width: 220,
                                                                fieldLabel: '结束时间',
                                                                id: 'voteEndtime',
                                                                name: 'voteEndtime',
                                                                format: 'Y-m-d'
                                                            },
                                                            {
                                                                xtype: 'gridpanel',
                                                                x: 140,
                                                                y: 210,
                                                                height: 319,
                                                                id: 'infoVoteoptionGrid1',
                                                                width: 590,
                                                                title: '',
                                                                store: voteOptionStore,
                                                                columns: [
                                                                {
                                                                    xtype: 'rownumberer'
                                                                },
                                                                {
                                                                    xtype: 'gridcolumn',
                                                                    dataIndex: 'voptionContent',
                                                                    text: '选项内容'
                                                                },
                                                                {
                                                                    xtype: 'gridcolumn',
                                                                    dataIndex: 'voptionNumber',
                                                                    text: '投票数目'
                                                                }
                                                                ],
                                                                dockedItems: [
                                                                {
                                                                    xtype: 'toolbar',
                                                                    dock: 'top',
                                                                    items: [
                                                                    {
                                                                        xtype: 'button',
                                                                        handler: function(button, event) {
                                                                            var voptionPanel = Ext.widget("infoVoteoptionShowTab");
                                                                            var voptionwin = new Ext.Window({

                                                                                title: '增加选项',
                                                                                closable: true,
                                                                                layout: 'fit',
                                                                                jsonSubmit: true,
                                                                                items:[

                                                                                {
                                                                                    xtype: 'form',
                                                                                    id: 'voptionForm',
                                                                                    layout: {
                                                                                        type: 'auto'
                                                                                    },
                                                                                    bodyPadding: 10,
                                                                                    jsonSubmit: true,
                                                                                    title: '',
                                                                                    items: [
                                                                                    {
                                                                                        xtype: 'textfield',
                                                                                        id: 'voptionContent',
                                                                                        width: 340,
                                                                                        fieldLabel: '投票选项',
                                                                                        name: 'voptionContent'
                                                                                    },
                                                                                    {
                                                                                        xtype: 'button',
                                                                                        handler: function(button, event) {
                                                                                            var myform = Ext.getCmp('voptionForm').getForm();

                                                                                            if (myform.isValid()) {
                                                                                                myform.submit({
                                                                                                    url:'add_voteoption2',
                                                                                                    params:{voteId:getVoteId},
                                                                                                    success: function(form, action) {
                                                                                                        Ext.Msg.alert('成功', '增加选项成功');

                                                                                                        voteOptionStore.load({
                                                                                                            params:{voteId:getVoteId}
                                                                                                        });
                                                                                                        voptionwin.close();

                                                                                                    },
                                                                                                    failure: function(form, action) {
                                                                                                        Ext.Msg.alert('失败', '修改内容失败');
                                                                                                        voptionwin.close();
                                                                                                    }
                                                                                                });
                                                                                            } else {
                                                                                                Ext.Msg.alert('注意', '填写信息不能为空，请检查！');
                                                                                            }

                                                                                            return;
                                                                                        },
                                                                                        text: '确定'
                                                                                    }
                                                                                    ]
                                                                                }



                                                                                ]
                                                                            });
                                                                            voptionwin.show();
                                                                        },
                                                                        text: '增加选项'
                                                                    },
                                                                    {
                                                                        xtype: 'button',
                                                                        handler: function(button, event) {
                                                                            var grid = Ext.getCmp('infoVoteoptionGrid1');

                                                                            var voptionrecord = grid.getSelectionModel().getSelection();

                                                                            if(voptionrecord.length === 0){
                                                                                Ext.Msg.alert('提示','请先选择您要操作的行！');
                                                                                return;

                                                                            }else{


                                                                                var  voptionIds =new Array(voptionrecord.length);
                                                                                for(var i = 0;i<voptionrecord.length;i++){
                                                                                    voptionIds[i] = voptionrecord[i].get("voptionId");

                                                                                }


                                                                                Ext.Ajax.request({
                                                                                    url:'del_voptionIds',
                                                                                    params:{voptionIds:voptionIds},

                                                                                    success:function(response){
                                                                                        Ext.Msg.alert('成功','删除成功');
                                                                                        voteOptionStore.load({
                                                                                            params:{voteId:getVoteId}
                                                                                        });

                                                                                    }

                                                                                });

                                                                            }
                                                                        },
                                                                        text: '删除选项'
                                                                    }
                                                                    ]
                                                                }
                                                                ],
                                                                selModel: Ext.create('Ext.selection.CheckboxModel', {

                                                                })
                                                            },
                                                            {
                                                                xtype: 'button',
                                                                handler: function(button, event) {
                                                                    var myform = Ext.getCmp('infoVoteUpdateForm').getForm();

                                                                    if (myform.isValid()) {
                                                                        myform.submit({
                                                                            url:'add_vote',
                                                                            success: function(form, action) {
                                                                                Ext.Msg.alert('成功', '修改成功');

                                                                                var mystore = Ext.StoreMgr.get('InfoVoteStore'); //获得store对象

                                                                                mystore.load();
                                                                                win.close();


                                                                            },
                                                                            failure: function(form, action) {
                                                                                Ext.Msg.alert('失败', '修改内容失败');

                                                                            }
                                                                        });
                                                                    } else {
                                                                        Ext.Msg.alert('注意', '填写信息不能为空，请检查！');
                                                                    }

                                                                    return;
                                                                },
                                                                x: 170,
                                                                y: 540,
                                                                text: '确定修改'
                                                            },
                                                            {
                                                                xtype: 'button',
                                                                hander:function(button, event) {
                                                                    win.close();
                                                                },
                                                                x: 380,
                                                                y: 540,
                                                                width: 80,
                                                                text: '取消'

                                                            }
                                                            ]
                                                        }


                                                        ]
                                                    });


                                                    Ext.getCmp('voteId').setValue(record[0].data.voteId);
                                                    Ext.getCmp('voteVoter').setValue(record[0].data.voteVoter);
                                                    Ext.getCmp('voteTitle').setValue(record[0].data.voteTitle);
                                                    Ext.getCmp('voteIntroduction').setValue(record[0].data.voteIntroduction);
                                                    Ext.getCmp('voteStarttime').setValue(record[0].data.voteStarttime);
                                                    Ext.getCmp('voteEndtime').setValue(record[0].data.voteEndtime);
                                                    Ext.getCmp('voteClass').setValue({voteClass:record[0].data.voteClass});
                                                    //Ext.getCmp('voteState').setValue(record[0].data.voteState);
                                                    win.show();


                                                }



                                            },
                                            icon: 'images/table_delete.png',
                                            text: '修改投票'
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, event) {
                                                var grid = Ext.getCmp('infoVoteGrid');

                                                var record = grid.getSelectionModel().getSelection();

                                                if(record.length === 0){
                                                    Ext.Msg.alert('提示','请先选择您要操作的行！');
                                                    return;

                                                }else{

                                                    var  voteIds =new Array(record.length);
                                                    for(var i = 0;i<record.length;i++){
                                                        voteIds[i] = record[i].get("voteId");

                                                    }




                                                    Ext.Ajax.request({
                                                        url:'del_voteByIds',
                                                        params:{voteIds:voteIds},

                                                        success:function(response){
                                                            Ext.Msg.alert('成功','投票已删除');
                                                            var mystore = Ext.StoreMgr.get('InfoVoteStore');
                                                            mystore.load();


                                                        }

                                                    });

                                                }
                                            },
                                            icon: 'images/table_delete.png',
                                            text: '删除投票'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'pagingtoolbar',
                                    dock: 'bottom',
                                    width: 360,
                                    displayInfo: true,
                                    store: 'InfoVoteStore'
                                }
                            ],
                            selModel: Ext.create('Ext.selection.CheckboxModel', {

                            }),
                            listeners: {
                                cellclick: {
                                    fn: me.onGridpanelCellClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onGridpanelCellClick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {
        if(cellIndex === undefined || cellIndex < 2) return;

        var getVoteId = record.data.voteId;
        var voteOptionStore = Ext.StoreMgr.get('InfoVoteoptionStore');
        voteOptionStore.load(
        {
            params:{voteId:getVoteId}
        }
        );

        var win = new Ext.Window({

            title: '查看投票信息',
            closable: true,
            layout: 'fit',
            jsonSubmit: true,
            items:[

            {
                xtype: 'form',
                layout: {
                    type: 'absolute'
                },
                bodyPadding: 10,
                title: '',
                items: [
                {
                    xtype: 'displayfield',
                    x: 40,
                    y: 10,
                    id: 'voteId',
                    width: 690,
                    fieldLabel: '投票id',
                    hidden:true,
                    name: 'voteId'
                },
                {
                    xtype: 'displayfield',
                    x: 40,
                    y: 10,
                    id: 'voteTitle',
                    width: 690,
                    fieldLabel: '投票主题',
                    name: 'voteTitle'
                },
                {
                    xtype: 'displayfield',
                    x: 40,
                    y: 40,
                    height: 100,
                    id: 'voteIntroduction',
                    width: 690,
                    fieldLabel: '投票简介',
                    name: 'voteIntroduction'
                },
                {
                    xtype: 'displayfield',
                    x: 40,
                    y: 150,
                    id: 'voteVoter',
                    width: 690,
                    fieldLabel: '发起人',
                    name: 'voteVoter'
                },
                {
                    xtype: 'displayfield',
                    x: 40,
                    y: 180,
                    id: 'voteStarttime',
                    width: 260,
                    fieldLabel: '开始时间',
                    name: 'voteStarttime'
                },
                {
                    xtype: 'displayfield',
                    x: 410,
                    y: 180,
                    id: 'voteEndtime',
                    width: 260,
                    fieldLabel: '结束时间',
                    name: 'voteEndtime'
                },
                {
                    xtype: 'displayfield',
                    x: 40,
                    y: 210,
                    id: 'voteClass',
                    width: 260,
                    fieldLabel: '投票类型',
                    name: 'voteClass'
                },
                {
                    xtype: 'displayfield',
                    x: 410,
                    y: 220,
                    id: 'voteState',
                    width: 260,
                    fieldLabel: '投票状态',
                    name: 'voteState'
                },
                {
                    xtype: 'displayfield',
                    x: 40,
                    y: 240,
                    width: 105,
                    fieldLabel: '投票结果'
                },
                {
                    xtype: 'chart',
                    x: 110,
                    y: 260,
                    height: 250,
                    width: 400,
                    animate: true,
                    insetPadding: 20,
                    store: voteOptionStore,
                    axes: [
                    {
                        type: 'Category',
                        fields: [
                        'voptionContent'
                        ],
                        position: 'left',
                        title: '投票选项'
                    },
                    {
                        type: 'Numeric',
                        fields: [
                        'voptionNumber'
                        ],
                        position: 'bottom',
                        title: '投票数量'
                    }
                    ],
                    series: [
                    {
                        type: 'bar',
                        label: {
                            display: 'insideEnd',
                            field: 'voptionNumber',
                            color: '#333',
                            'text-anchor': 'middle'
                        },
                        axis: 'bottom',
                        xField: 'voptionContent',
                        yField: 'voptionNumber'
                    }
                    ]
                }
                ]
            }


            ]
        });

        Ext.getCmp('voteId').setValue(record.data.voteId);
        Ext.getCmp('voteVoter').setValue(record.data.voteVoter);
        Ext.getCmp('voteTitle').setValue(record.data.voteTitle);
        Ext.getCmp('voteIntroduction').setValue(record.data.voteIntroduction);
        Ext.getCmp('voteStarttime').setValue(record.data.voteStarttime);
        Ext.getCmp('voteEndtime').setValue(record.data.voteEndtime);
        Ext.getCmp('voteClass').setValue(record.data.voteClass);
        Ext.getCmp('voteState').setValue(record.data.voteState);
        win.show();




    }

});