/*
 * File: app/view/InfoEditWin.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.InfoEditWin', {
    extend: 'Ext.window.Window',
    alias: 'widget.InfoEditWin',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.form.field.HtmlEditor',
        'Ext.button.Button',
        'Ext.Img',
        'Ext.form.Label'
    ],

    height: 560,
    width: 800,
    title: '信息发布',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    height: 527,
                    fixed: true,
                    autoScroll: true,
                    layout: 'absolute',
                    bodyPadding: 10,
                    title: '',
                    items: [
                        {
                            xtype: 'textfield',
                            x: 20,
                            y: 10,
                            width: 400,
                            fieldLabel: '标题',
                            labelWidth: 40,
                            name: 'title'
                        },
                        {
                            xtype: 'textfield',
                            x: 20,
                            y: 40,
                            width: 400,
                            fieldLabel: '来源',
                            labelWidth: 40,
                            name: 'source'
                        },
                        {
                            xtype: 'textfield',
                            x: 20,
                            y: 70,
                            width: 400,
                            fieldLabel: '作者',
                            labelWidth: 40,
                            name: 'author'
                        },
                        {
                            xtype: 'combobox',
                            x: 20,
                            y: 100,
                            width: 400,
                            fieldLabel: '栏目',
                            labelWidth: 40,
                            name: 'chanel',
                            listeners: {
                                select: {
                                    fn: me.onComboboxSelect,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'htmleditor',
                            x: 20,
                            y: 130,
                            height: 350,
                            width: 740,
                            fixed: true,
                            fieldLabel: '内容',
                            labelWidth: 40,
                            name: 'content'
                        },
                        {
                            xtype: 'button',
                            x: 510,
                            y: 10,
                            width: 80,
                            text: '上传图片'
                        },
                        {
                            xtype: 'button',
                            x: 70,
                            y: 490,
                            width: 80,
                            text: '保存'
                        },
                        {
                            xtype: 'button',
                            x: 190,
                            y: 490,
                            width: 80,
                            text: '取消'
                        },
                        {
                            xtype: 'image',
                            x: 600,
                            y: 10,
                            height: 120,
                            width: 160
                        },
                        {
                            xtype: 'label',
                            x: 480,
                            y: 100,
                            height: 20,
                            text: '* 拖拽图片至内容中'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onComboboxSelect: function(combo, records, eOpts) {
         var projectname=records[0].get('projectname');
                Ext.Ajax.request({
                    url:'get_projectIDList',
                    params:{projectName:projectname},
                    success:function(response){
                        var u =Ext.JSON.decode(response.responseText);
                        Ext.getCmp("prjid").setValue(u.projectId);
                    }
                });
    }

});