/*
 * File: app/view/manageProjectDikuai.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.manageProjectDikuai', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.manageProjectDikuai',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.RowNumberer',
        'Ext.grid.View',
        'Ext.button.Button',
        'Ext.form.field.Text',
        'Ext.toolbar.Paging',
        'Ext.selection.CheckboxModel'
    ],

    layout: 'fit',
    title: '项目片块管理',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    frame: true,
                    height: 150,
                    id: 'projectDikuaiGrid',
                    title: '',
                    subGridXType: '',
                    columnLines: true,
                    store: 'FkProjectDikuaiStore',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            hidden: true,
                            dataIndex: 'recordId',
                            text: '记录号'
                        },
                        {
                            xtype: 'rownumberer'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'landId',
                            text: '片块号'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'projectId',
                            text: '项目编号'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'projectname',
                            text: '项目名称'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'personRights',
                            text: '权利人'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'ownershipUnits',
                            text: '土地产权属性'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'propertyNumber',
                            text: '宅基地产权证号'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'fuKenhouPropertyNumber',
                            text: '复垦后产权证号'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'landLocation',
                            text: '片块位置'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'fukenArea',
                            text: '片块面积'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'mapSheetNumber',
                            text: '图幅号'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'polygonNumber',
                            text: '图斑号'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'fukenqianLandUse',
                            text: '复垦前土地利用类型'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'newHousingArea',
                            text: '新建住房占地'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'newHousingArea',
                            text: '增加耕地面积'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'whereAbouts',
                            text: '去向'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                return "<img src='Upload/before/zjd.jpg' />";
                            },
                            text: '土地使用证'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        var tabs = this.up('tabpanel');
                                        tabs.removeAll(true);
                                        //用tabs.add()新增加一个tab页面,通过Ext.widget(xtype)得到文章回收站的页面
                                        var newtab = tabs.add(Ext.widget('addFkdikuai'));
                                    },
                                    icon: 'images/table_add.png',
                                    text: '添加片块信息'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        var grid = Ext.getCmp('projectDikuaiGrid');
                                        var record = grid.getSelectionModel().getSelection();
                                        var projectSelectedId = record[0].get("recordId");
                                        if (record.length == 0) {
                                            Ext.Msg.alert('提示', '请先选择您要操作的行!'+0);
                                            return;

                                        } else if (record.length > 1) {
                                            Ext.Msg.alert('提示', '只能选择一行数据');
                                            return;
                                        } else {
                                            Ext.Msg.alert('提示', projectSelectedId);
                                            var tabs = this.up('tabpanel');
                                            tabs.removeAll(true);
                                            var newtab = tabs.add(Ext.widget('updateFkdikuai'));

                                            var updateFkdikuaiForm = newtab.getComponent('updateFkdikuaiForm');
                                            Ext.Msg.alert('提示', updateFkdikuaiForm.id);
                                            updateFkdikuaiForm.load({
                                                params: {
                                                    dikuaiSelectedId: projectSelectedId
                                                },
                                                url:'get_dikuaiDetail',
                                                method:'GET',
                                                success:function(form,action){
                                                    Ext.Msg.alert('提示','数据加载成功');
                                                },
                                                failure:function(form,action){
                                                    Ext.Msg.alert('提示','数据加载失败');
                                                }
                                            });

                                        }
                                    },
                                    icon: 'images/table_edit.png',
                                    iconCls: 'imgs/table/table_edit.png',
                                    text: '编辑地块信息'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        var grid = Ext.getCmp('projectDikuaiGrid');
                                        var record = grid.getSelectionModel().getSelection();
                                        if(record.length === 0){
                                            Ext.Msg.alert('提示','请先选择您要操作的行！');
                                            return;

                                        }else{

                                            var  projectIds =new Array(record.length);
                                            for(var i = 0;i<record.length;i++){
                                                projectIds[i] = record[i].get("recordId");

                                            }
                                            //Ext.Msg.alert('提示',projectIds);

                                            Ext.Ajax.request({
                                                url:'del_dikuaiByIds',
                                                params:{projectIds:projectIds},

                                                success:function(response){
                                                    Ext.Msg.alert('success','地块已删除');
                                                    var mystore = Ext.StoreMgr.get('FkProjectDikuaiStore');
                                                    mystore.load();


                                                }

                                            });

                                        }
                                    },
                                    icon: 'images/table_delete.png',
                                    iconCls: 'imgs/table/table_delete.png',
                                    text: '删除片块信息'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        var tabs=this.up('tabpanel');
                                        tabs.removeAll(true);
                                        var newtab= tabs.add(Ext.widget('manageProject'));
                                    },
                                    icon: 'images/return.png',
                                    iconCls: 'images/file_view0.png',
                                    text: '返回到项目管理'
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'searchKeywordDikuai',
                                    fieldLabel: '项目编号',
                                    name: 'searchKeyword1',
                                    inputId: '',
                                    emptyText: '请输入查询关键字'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        //var getKeyword = Ext.getCmp('searchKeyword1').getValue();
                                        //Ext.Msg.alert(getKeyword);
                                        var mystore=Ext.StoreMgr.get('FkProjectDikuaiStore');//获得store对象
                                        //Ext.Msg.alert('11',mystore);

                                        //在load事件中添加参数
                                        mystore.load(
                                        {params:{
                                            start:"0",
                                            limit:"25",
                                            searchKeywordName:Ext.getCmp('searchKeywordDikuai').getValue()
                                        }
                                    }
                                    );
                                    },
                                    id: 'searchProject5',
                                    text: '查询'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        var win=new Ext.Window({
                                            height: 412,
                                            width: 334,
                                            layout: {
                                                type: 'absolute'
                                            },
                                            title: '高级查询',

                                            modal: true,
                                            items: [
                                            {
                                                xtype: 'textfield',
                                                x: 30,
                                                y: 70,
                                                id: 'projectSearchName',
                                                fieldLabel: '地块编号'
                                            },
                                            {
                                                xtype: 'textfield',
                                                x: 30,
                                                y: 110,
                                                id: 'projectSearchID',
                                                fieldLabel: '权利人'
                                            },
                                            {
                                                xtype: 'textfield',
                                                x: 30,
                                                y: 230,
                                                id: 'projectSearchSite',
                                                fieldLabel: '地块区域'
                                            },
                                            {
                                                xtype: 'label',
                                                x: 30,
                                                y: 30,
                                                shrinkWrap: 3,
                                                text: '请设置项目高级查询参数：'
                                            },
                                            {
                                                xtype: 'textfield',
                                                x: 30,
                                                y: 150,
                                                id: 'projectSearchStarttime',
                                                fieldLabel: '项目编号'
                                            },
                                            {
                                                xtype: 'textfield',
                                                x: 30,
                                                y: 190,
                                                id: 'projectSearchFinishtime',
                                                fieldLabel: '项目名称'
                                            },
                                            {
                                                xtype: 'button',
                                                handler: function(button, event) {

                                                    var mystore=Ext.StoreMgr.get('FkProjectDikuaiStore');//获得store对象

                                                    mystore.load(
                                                    {params:{
                                                        start:"0",
                                                        limit:"25",
                                                        searchKeywordName:Ext.getCmp('projectSearchName').getValue(),
                                                        searchKeywordID:Ext.getCmp('projectSearchID').getValue(),
                                                        searchKeywordSite:Ext.getCmp('projectSearchSite').getValue(),
                                                        searchKeywordStarttime:Ext.getCmp('projectSearchStarttime').getValue(),
                                                        searchKeywordFinishtime:Ext.getCmp('projectSearchFinishtime').getValue()
                                                    }
                                                }
                                                );
                                            },
                                            x: 120,
                                            y: 300,
                                            text: '查询'
                                        }
                                        ]
                                    });

                                    win.show();

                                    },
                                    id: 'searchProject6',
                                    text: '高级查询'
                                }
                            ]
                        },
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'FkProjectDikuaiStore'
                        }
                    ],
                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                    })
                }
            ]
        });

        me.callParent(arguments);
    }

});