/*
 * File: app/view/ManagAcceptApply.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ManagAcceptApply', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.ManagAcceptApply',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.column.Date',
        'Ext.grid.View',
        'Ext.button.Button',
        'Ext.form.field.Text',
        'Ext.toolbar.Paging',
        'Ext.selection.CheckboxModel'
    ],

    layout: 'border',
    title: '复垦验收申请',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    region: 'north',
                    frame: true,
                    height: 241,
                    id: 'applyGrid',
                    title: '未审核申请列表',
                    subGridXType: '',
                    columnLines: true,
                    store: 'FkacceptApplyStore',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'applyId',
                            text: '申请编号'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'projectId',
                            text: '复垦项目编号'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 260,
                            dataIndex: 'projectname',
                            text: '复垦项目名称'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 200,
                            dataIndex: 'conUnit',
                            text: '项目施工单位'
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'applyDate',
                            text: '提交申请日期',
                            format: 'Y-m-d'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'note',
                            text: '备注信息'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 120,
                            dataIndex: 'fileCheck',
                            text: '申请文件已上传'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'checkResult',
                            text: '审核结果'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        var tabs = this.up('tabpanel');
                                        tabs.removeAll(true);
                                        //用tabs.add()新增加一个tab页面,通过Ext.widget(xtype)得到文章回收站的页面
                                        var newtab = tabs.add(Ext.widget('acceptApply'));
                                    },
                                    icon: 'images/table_add.png',
                                    text: '验收申请'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        var grid = Ext.getCmp('applyGrid');
                                        var record = grid.getSelectionModel().getSelection();
                                        if(record.length === 0){
                                            Ext.Msg.alert('提示','请先选择您要操作的行！');
                                            return;

                                        }else{

                                            var  applyIds =new Array(record.length);
                                            for(var i = 0;i<record.length;i++){
                                                applyIds[i] = record[i].get("applyId");
                                            }
                                            Ext.Ajax.request({
                                                url:'del_applyByIds',
                                                params:{applyIds:applyIds},

                                                success:function(response){
                                                    Ext.Msg.alert('success','申请已删除');
                                                    var mystore = Ext.StoreMgr.get('FkacceptApplyStore');
                                                    mystore.load();


                                                }

                                            });

                                        }
                                    },
                                    icon: 'images/table_delete.png',
                                    iconCls: 'imgs/table/table_delete.png',
                                    text: '删除申请'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        var grid = Ext.getCmp('applyGrid');
                                        var record = grid.getSelectionModel().getSelection();
                                        var applySelectedId = record[0].get("applyId");
                                        var projectSelectedId = record[0].get("projectId");
                                        var applySelectedName = record[0].get("projectname");

                                        var tabs = this.up('tabpanel');
                                        tabs.removeAll(true);
                                        //用tabs.add()新增加一个tab页面,通过Ext.widget(xtype)得到文章回收站的页面
                                        var newtab = tabs.add(Ext.widget('checkApply'));

                                        Ext.getCmp('checkApplyId').setValue(applySelectedId);
                                        Ext.getCmp('applyprojectId').setValue(projectSelectedId);
                                        Ext.getCmp('applyProjectname').setValue(applySelectedName);

                                    },
                                    icon: '',
                                    iconCls: '',
                                    text: '审核申请'
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'searchKeyword2',
                                    fieldLabel: '申请编号',
                                    name: 'searchKeyword2',
                                    inputId: '',
                                    emptyText: '请输入查询关键字'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        //var getKeyword = Ext.getCmp('searchKeyword1').getValue();
                                        //Ext.Msg.alert(getKeyword);
                                        var mystore=Ext.StoreMgr.get('FkacceptApplyStore');//获得store对象
                                        //Ext.Msg.alert('11',mystore);

                                        //在load事件中添加参数
                                        mystore.load(
                                        {params:{
                                            start:"0",
                                            limit:"25",
                                            searchKeyword:Ext.getCmp('searchKeyword2').getValue()
                                        }
                                    }
                                    );
                                    },
                                    id: 'searchProject1',
                                    text: '查询'
                                }
                            ]
                        },
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            id: 'MyapplyPage',
                            width: 360,
                            displayInfo: true,
                            store: 'FkacceptApplyStore'
                        }
                    ],
                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                    })
                },
                {
                    xtype: 'gridpanel',
                    region: 'north',
                    frame: true,
                    height: 241,
                    id: 'applyGrid1',
                    title: '已审核申请列表',
                    subGridXType: '',
                    columnLines: true,
                    store: 'FkacceptCheckStore',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'applyId',
                            text: '申请编号'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'projectId',
                            text: '复垦项目编号'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 260,
                            dataIndex: 'projectname',
                            text: '复垦项目名称'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 200,
                            dataIndex: 'conUnit',
                            text: '项目施工单位'
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'applyDate',
                            text: '提交申请日期',
                            format: 'Y-m-d'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'note',
                            text: '备注信息'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 120,
                            dataIndex: 'fileCheck',
                            text: '申请文件已上传'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'checkResult',
                            text: '审核结果'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        var tabs = this.up('tabpanel');
                                        tabs.removeAll(true);
                                        //用tabs.add()新增加一个tab页面,通过Ext.widget(xtype)得到文章回收站的页面
                                        var newtab = tabs.add(Ext.widget('acceptApply'));
                                    },
                                    icon: 'images/table_add.png',
                                    text: '验收申请'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        var grid = Ext.getCmp('applyGrid1');
                                        var record = grid.getSelectionModel().getSelection();
                                        if(record.length === 0){
                                            Ext.Msg.alert('提示','请先选择您要操作的行！');
                                            return;

                                        }else{

                                            var  applyIds =new Array(record.length);
                                            for(var i = 0;i<record.length;i++){
                                                applyIds[i] = record[i].get("applyId");
                                            }
                                            Ext.Ajax.request({
                                                url:'del_applyByIds',
                                                params:{applyIds:applyIds},

                                                success:function(response){
                                                    Ext.Msg.alert('success','申请已删除');
                                                    var mystore = Ext.StoreMgr.get('FkacceptCheckStore');
                                                    mystore.load();


                                                }

                                            });

                                        }
                                    },
                                    icon: 'images/table_delete.png',
                                    iconCls: 'imgs/table/table_delete.png',
                                    text: '删除申请'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        var grid = Ext.getCmp('applyGrid1');
                                        var record = grid.getSelectionModel().getSelection();
                                        var applySelectedId = record[0].get("applyId");
                                        var projectSelectedId = record[0].get("projectId");
                                        var applySelectedName = record[0].get("projectname");

                                        var tabs = this.up('tabpanel');
                                        tabs.removeAll(true);
                                        //用tabs.add()新增加一个tab页面,通过Ext.widget(xtype)得到文章回收站的页面
                                        var newtab = tabs.add(Ext.widget('checkApply'));

                                        Ext.getCmp('checkApplyId').setValue(applySelectedId);
                                        Ext.getCmp('applyprojectId').setValue(projectSelectedId);
                                        Ext.getCmp('applyProjectname').setValue(applySelectedName);

                                        SetLayerNameById('checkApplyDiv');
                                    },
                                    icon: '',
                                    iconCls: '',
                                    text: '审核申请'
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'searchKeyword4',
                                    fieldLabel: '申请编号',
                                    name: 'searchKeyword2',
                                    inputId: '',
                                    emptyText: '请输入查询关键字'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {

                                        var mystore=Ext.StoreMgr.get('FkacceptCheckStore');//获得store对象

                                        mystore.load(
                                        {params:{
                                            start:"0",
                                            limit:"25",
                                            searchKeyword:Ext.getCmp('searchKeyword4').getValue()
                                        }
                                    }
                                    );
                                    },
                                    id: 'searchProject3',
                                    text: '查询'
                                }
                            ]
                        },
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            id: 'MyapplyPage2',
                            width: 360,
                            displayInfo: true,
                            store: 'FkacceptCheckStore'
                        }
                    ],
                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                    })
                }
            ]
        });

        me.callParent(arguments);
    }

});