/*
 * File: app/view/sampleDataManage.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.sampleDataManage', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.sampleDataManage',

    requires: [
        'Ext.form.Panel',
        'Ext.grid.Panel',
        'Ext.grid.RowNumberer',
        'Ext.grid.column.Date',
        'Ext.grid.View',
        'Ext.form.field.Text',
        'Ext.button.Button',
        'Ext.toolbar.Paging',
        'Ext.selection.CheckboxModel'
    ],

    layout: 'fit',
    title: '采样点数据管理',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    height: 140,
                    id: 'sampleDataManageForm',
                    layout: 'fit',
                    bodyPadding: 10,
                    title: '',
                    items: [
                        {
                            xtype: 'gridpanel',
                            id: 'sampleDataManageGrid',
                            title: '',
                            store: 'SampleStore',
                            columns: [
                                {
                                    xtype: 'rownumberer'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    dataIndex: 'recordId',
                                    text: '记录号'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'sampleId',
                                    text: '样品编号'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'sampleAddresss',
                                    text: '采集地点'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'projectId',
                                    text: '项目编号'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'projectName',
                                    text: '项目名称'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'soilThickness',
                                    text: '土层厚度'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'soilmoisture',
                                    text: '土壤含水量'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'soiltexture',
                                    text: '土壤质地'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'longitude',
                                    text: '经度'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'latitude',
                                    text: '纬度'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'organicmatter',
                                    text: '有机质'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'phvalue',
                                    text: 'pH值'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'totalnitrogen',
                                    text: '全氮'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'totalphosphorus',
                                    text: '全磷'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'totalpotassium',
                                    text: '全钾'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'recorder',
                                    text: '记录人'
                                },
                                {
                                    xtype: 'datecolumn',
                                    dataIndex: 'sampletime',
                                    text: '采样时间',
                                    format: 'Y-m-d'
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            id: 'sampleSearch',
                                            fieldLabel: '项目编号',
                                            name: 'sampleSearch'
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, event) {
                                                //var getKeyword = Ext.getCmp('searchKeyword1').getValue();
                                                //Ext.Msg.alert(getKeyword);
                                                var mystore=Ext.StoreMgr.get('SampleStore');//获得store对象
                                                //Ext.Msg.alert('11',mystore);

                                                //在load事件中添加参数
                                                mystore.load(
                                                {params:{
                                                    start:"0",
                                                    limit:"25",
                                                    searchKeyword:Ext.getCmp('sampleSearch').getValue()
                                                }
                                            }
                                            );
                                            },
                                            text: '查询'
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, event) {
                                                var tabs = this.up('tabpanel');
                                                tabs.removeAll(true);
                                                //用tabs.add()新增加一个tab页面,通过Ext.widget(xtype)得到文章回收站的页面
                                                var newtab = tabs.add(Ext.widget('sampleDataAdd'));
                                            },
                                            icon: 'images/table_add.png',
                                            text: '添加',
                                            listeners: {
                                                click: {
                                                    fn: me.onButtonClick,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, event) {
                                                var grid = Ext.getCmp('sampleDataManageGrid');
                                                var record = grid.getSelectionModel().getSelection();
                                                var projectSelectedId = record[0].get("recordId");
                                                if (record.length === 0) {
                                                    Ext.Msg.alert('提示', '请先选择您要操作的行！');
                                                    return;

                                                } else if (record.length > 1) {
                                                    Ext.Msg.alert('提示', '只能选择一行数据');
                                                    return;
                                                } else {
                                                    Ext.Msg.alert('提示', projectSelectedId);
                                                    var tabs = this.up('tabpanel');
                                                    tabs.removeAll(true);
                                                    var newtab = tabs.add(Ext.widget('sampleDataUpdate'));


                                                    var sampleDataUpdateform = newtab.getComponent('sampleDataUpdateform');
                                                    Ext.Msg.alert('提示', sampleDataUpdateform.id);
                                                    sampleDataUpdateform.load({
                                                        params: {
                                                            projectSelectedId: projectSelectedId
                                                        },
                                                        url:'get_sampleDetail',
                                                        method:'GET',
                                                        success:function(form,action){
                                                            Ext.Msg.alert('提示','数据加载成功');
                                                        },
                                                        failure:function(form,action){
                                                            Ext.Msg.alert('提示','数据加载失败');
                                                        }
                                                    });



                                                }
                                            },
                                            icon: 'images/table_edit.png',
                                            text: '编辑'
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, event) {
                                                var grid = Ext.getCmp('sampleDataManageGrid');
                                                var record = grid.getSelectionModel().getSelection();
                                                if(record.length === 0){
                                                    Ext.Msg.alert('提示','请先选择您要操作的行！');
                                                    return;

                                                }else{

                                                    var  sampleIds =new Array(record.length);
                                                    for(var i = 0;i<record.length;i++){
                                                        sampleIds[i] = record[i].get("recordId");

                                                    }
                                                    //Ext.Msg.alert('提示',projectIds);

                                                    Ext.Ajax.request({
                                                        url:'del_sampleByIds',
                                                        params:{sampleIds:sampleIds},

                                                        success:function(response){
                                                            Ext.Msg.alert('success','样点已删除');
                                                            var mystore = Ext.StoreMgr.get('SampleStore');
                                                            mystore.load();


                                                        }

                                                    });

                                                }
                                            },
                                            icon: 'images/table_delete.png',
                                            text: '删除'
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, event) {
                                                //显示地图窗口
                                                var win=new Ext.Window({
                                                    height: 620,
                                                    width: 810,
                                                    title: '采样点空间分布图',
                                                    closable: true,
                                                    layout: 'fit',
                                                    jsonSubmit: true,
                                                    items: [
                                                    {
                                                        xtype: 'form',
                                                        html: '<div id="mapdiv_SampleData" class="MapClass"> </div>',
                                                        height: 610,
                                                        layout: {
                                                            type: 'absolute'
                                                        },
                                                        bodyPadding: 10,
                                                        title: '',
                                                        listeners: {
                                                            afterrender: function(){
                                                                //console.log("渲染会");

                                                                //加入地图的js文件
                                                                var head = document.getElementsByTagName('head')[0];
                                                                var script= document.createElement("script");
                                                                script.type = "text/javascript";
                                                                script.src="map/sampleData_map.js";
                                                                head.appendChild(script);
                                                            }
                                                        }
                                                    }
                                                    ]
                                                });
                                                win.show();
                                            },
                                            icon: 'images/file_view0.png',
                                            text: '查看采样点空间分布图'
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, event) {
                                                var tabs = this.up('tabpanel');
                                                tabs.removeAll(true);
                                                var newtab = tabs.add(Ext.widget('EvaluateSelectProject'));
                                            },
                                            icon: 'images/return.png',
                                            text: '返回'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'pagingtoolbar',
                                    dock: 'bottom',
                                    width: 360,
                                    displayInfo: true,
                                    store: 'SampleStore'
                                }
                            ],
                            selModel: Ext.create('Ext.selection.CheckboxModel', {

                            })
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {

    }

});