/*
 * File: app/view/TaishiArea.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.TaishiArea', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.TaishiArea',

    requires: [
        'Ext.panel.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date',
        'Ext.toolbar.Separator',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio'
    ],

    height: 631,
    width: 1043,
    layout: 'border',
    title: '按交易区域分析',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    region: 'center',
                    html: '<div id = "mapDiv_taishiArea" style = "width=100%;height:100%;">\r\n        <!--<div id="bottomPanel">-->\r\n            <!--<div id="timeInfo">-->\r\n                <!--<div>统计从 <span id="taishi_daterange">2009 到 2011</span> 间的数据</div>-->\r\n                <!--<div id="taishi_timeSliderDiv"></div>-->\r\n            <!--</div>-->\r\n        <!--</div>-->\r\n        <!--<div id="info">-->\r\n            <!--<div id="legend_taishi"></div>-->\r\n        <!--</div>-->\r\n</div>',
                    title: '按交易区域分析图',
                    listeners: {
                        afterrender: {
                            fn: me.onPanelAfterRender,
                            scope: me
                        }
                    }
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'combobox',
                            id: 'taishiArea_renderArea',
                            width: 160,
                            fieldLabel: '交易区域',
                            labelWidth: 60,
                            value: '长寿区'
                        },
                        {
                            xtype: 'datefield',
                            id: 'taishi_minDate',
                            width: 120,
                            fieldLabel: '从',
                            labelWidth: 25,
                            value: '2014-01-01',
                            format: 'Y-m-d'
                        },
                        {
                            xtype: 'datefield',
                            id: 'taishi_maxDate',
                            width: 120,
                            fieldLabel: '到',
                            labelWidth: 25,
                            value: '2014-06-30',
                            format: 'Y-m-d'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'radiogroup',
                            id: 'radioGroup_taishiArea',
                            width: 300,
                            fieldLabel: '查看专题图',
                            labelWidth: 70,
                            items: [
                                {
                                    xtype: 'radiofield',
                                    id: 'radio_TradeVolume',
                                    name: 'taishiArea',
                                    boxLabel: '交易量',
                                    inputValue: 'volume'
                                },
                                {
                                    xtype: 'radiofield',
                                    id: 'radio_TradeNumber',
                                    name: 'taishiArea',
                                    boxLabel: '交易次数',
                                    inputValue: 'number'
                                },
                                {
                                    xtype: 'radiofield',
                                    id: 'radio_TradePrice',
                                    name: 'taishiArea',
                                    boxLabel: '交易价格',
                                    inputValue: 'price'
                                }
                            ],
                            listeners: {
                                change: {
                                    fn: me.onRadioGroup_taishiAreaChange,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'radiogroup',
                            id: 'radioGroup_taishiRender',
                            width: 300,
                            fieldLabel: '专题图样式',
                            labelWidth: 70,
                            items: [
                                {
                                    xtype: 'radiofield',
                                    name: 'renderType',
                                    boxLabel: '分级符号',
                                    checked: true,
                                    inputValue: 'symbol'
                                },
                                {
                                    xtype: 'radiofield',
                                    name: 'renderType',
                                    boxLabel: '分级彩色',
                                    inputValue: 'color'
                                },
                                {
                                    xtype: 'radiofield',
                                    hidden: true,
                                    name: 'renderType',
                                    boxLabel: '点密度',
                                    inputValue: 'dot'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onPanelAfterRender: function(component, eOpts) {
        //加入地图的js文件
        var head = document.getElementsByTagName('head')[0];
        var script= document.createElement("script");
        script.type = "text/javascript";
        script.src="map/taishiArea_map.js";
        head.appendChild(script);
    },

    onRadioGroup_taishiAreaChange: function(field, newValue, oldValue, eOpts) {
        //var renderType = newValue.taishiArea;	//获取选中的统计量
        //SetRenderType(renderType);				//设置渲染方式
        //InitStatisticAndRenderMap();		//渲染地图
    }

});