/*
 * File: app/view/tpApplyRecl.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.tpApplyRecl', {
    extend: 'Ext.tree.Panel',
    alias: 'widget.mytreepanel3',

    id: 'tpApplyRecl',
    title: '申请拆迁（复垦）',
    store: 'treestoreApplyRecl',
    rootVisible: false,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            viewConfig: {
                listeners: {
                    itemclick: {
                        fn: me.onViewItemClick,
                        scope: me
                    }
                }
            }
        });

        me.callParent(arguments);
    },

    onViewItemClick: function(dataview, record, item, index, e, eOpts) {
        Ext.getCmp("body").getLayout().setActiveItem(3);
        switch(record.raw.id)
        {
            case 401:Ext.getCmp("application").getLayout().setActiveItem(0);break;
            case 402:Ext.getCmp("application").getLayout().setActiveItem(1);break;
            case 403:
            	{
  
            	var appStore = Ext.create('Ext.data.Store', {
   
            	    proxy: {
            	        // load using HTTP
            	        type: 'ajax',
            	        url: 'showAppByID.action',  
            	        // the return will be XML, so lets set up a reader
            	        reader:{
                			type:"json",
                			root:"results",
                			totalProperty :'totalCount'		
                		},
                		actionMethods: {  
                            read: 'POST'  
                        },
                		writer:{
                			type:"json"
                		}
            	    },
            	    listeners:{
            	    	beforeload:function(){
            	    	msgTip = Ext.MessageBox.show({
		            	    	title:'提示',
		            	    	width : 250,
		            	    	msg:'加载中,请稍后......'
	            	    	});
            	    	}
            	    },
                    fields: [
            		        {name: 'name',  type: 'string', useNull: true},  
                 	        {name: 'card',  type: 'string'},  
                 	        {name: 'address',  type: 'string'},
                 	        {name: 'applicationAddress', type: 'string'},
                 	        {name: 'productID', type: 'string'},
                 	        {name: 'phone', type: 'string'},
                 	        {name: 'totalArea', type: 'auto'},
                 	        {name: 'bulidArea', type: 'auto'},
                 	        {name: 'productDate', type: 'date',
                 	        	mapping: 'productDate.time',  dateFormat : 'time'},
                 	        {name: 'applicationDate', type: 'date',
                 	        	mapping: 'applicationDate.time',  dateFormat : 'time'},
                 	        {name: 'north', type: 'auto'},
                 	        {name: 'south', type: 'auto'},
                 	        {name: 'west', type: 'auto'},
                 	        {name: 'east', type: 'auto'},
                 	        {name: 'work', type: 'string'},
                 	        {name: 'afterUse', type: 'string'},
                 	        {name: 'belongUse', type: 'string'},
                 	        {name: 'reword', type: 'string'},
                 	        {name: 'isAgreeSelf', type: 'string'},
                 	        {name: 'isAgreeVillage', type: 'string'},
                 	        {name: 'isAgreeTown', type: 'string'},
                 	        {name: 'content', type: 'string'},
                 	        ]
            	    
            	});
            	    
            		
            	    
            		appStore.load({
	            		callback: function(records, options, success){
	            			
	          
	                		//遍历store
	                		appStore.each(function(record) {
	                
	                			//重写radiogroup的 setValue()方法。
	                	        Ext.override(Ext.form.RadioGroup,{   
	                	            setValue: function(v){   	                	            		                	                   
	                	            	v = v.replace( /^\s+|\s+$/g, "" );
	                	                this.items.each(function(item,index,length){ 
	                	                	
	                	                	
	                			            if (v == item.boxLabel){  	
	                			      
	                			                item.checked = true;   		            
	                			            }
	                
	                			      
	                	                });
	                	             
	                	            },   
	                	        });
	                			
	       
	    	            	    Ext.getCmp("appliName1").setValue(record.get("name"));	    	            	    
	    	            	    Ext.getCmp("appliID1").setValue(record.get("card"));
	    	                	Ext.getCmp("appliAddress1").setValue(record.get("address"));
	    	                	Ext.getCmp("appliLocate1").setValue(record.get("applicationAddress"));
	    	                	Ext.getCmp("appliTel1").setValue(record.get("phone"));
	    	                	Ext.getCmp("appliNumber1").setValue(record.get("productID"));
	    	                	Ext.getCmp("areaTotle1").setValue(record.get("totalArea"));
	    	                	Ext.getCmp("area1").setValue(record.get("bulidArea"));
	    	                	Ext.getCmp("startTime1").setValue(record.get("productDate"));
	    	                	Ext.getCmp("appliTime1").setValue(record.get("applicationDate"));
	    	                		    	                	
	    	                	//四至范围
	    	                	Ext.getCmp("toNorth1").setValue(record.get("north"));
	    	                	Ext.getCmp("toSouth1").setValue(record.get("south"));
	    	                	Ext.getCmp("toWest1").setValue(record.get("west"));
	    	                	Ext.getCmp("toEast1").setValue(record.get("east"));
	    	                	
	    	                	
	    	                	Ext.getCmp("mode1").setValue(record.get("work"));
	    	                	Ext.getCmp("usage1").setValue(record.get("afterUse"));
	    	                	Ext.getCmp("ownership1").setValue(record.get("belongUse"));
	    	                	Ext.getCmp("payments1").setValue(record.get("reword"));
	    	                	Ext.getCmp("agreement3").setValue(record.get("isAgreeSelf"));
	    	                	Ext.getCmp("agreement4").setValue(record.get("isAgreeVillage"));
	    	                	Ext.getCmp("agreement5").setValue(record.get("isAgreeTown"));
	    	                	
	    	                	Ext.getCmp("contentOthers1").setValue(record.get("content"));
	    	            	    
	    	            	    
	                		});
	            			
	                		msgTip.hide(); // 加载完成，关闭提示框
	                		Ext.getCmp("application").getLayout().setActiveItem(2);       		
	                		
	            		}
            		});
            		
            		
            		break;
            	}
            case 404:Ext.getCmp("application").getLayout().setActiveItem(3);break;
            case 405:Ext.getCmp("application").getLayout().setActiveItem(4);break;

        }
    }

});