/*
 * File: app/view/tpPreWarm.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.tpPreWarm', {
    extend: 'Ext.tree.Panel',
    alias: 'widget.mytreepanel6',

    id: 'tpPreWarn',
    title: '预警',
    store: 'treestorePreWarn',
    rootVisible: false,

    initComponent: function() {
        var me = this;
  
        Ext.applyIf(me, {
            viewConfig: {
                listeners: {
                    itemclick: {
                        fn: me.onViewItemClick,
                        scope: me
                    }
                }
            }
        });

        me.callParent(arguments);
    },

    onViewItemClick: function(dataview, record, item, index, e, eOpts) {
        Ext.getCmp("body").getLayout().setActiveItem(7);
        switch(record.raw.id)
        {
            case 801:
            	Ext.getCmp("PreWarm").getLayout().setActiveItem(0);

            	break;
            case 802:Ext.getCmp("PreWarm").getLayout().setActiveItem(1);break;
            case 803:Ext.getCmp("PreWarm").getLayout().setActiveItem(2);break;
            case 804:Ext.getCmp("PreWarm").getLayout().setActiveItem(3);break;
            case 805:Ext.getCmp("PreWarm").getLayout().setActiveItem(4);break;

        }
    }

});