/*
 * File: app/view/use_MonitorResult.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.use_MonitorResult', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.use_MonitorResult',

    requires: [
        'Ext.form.field.Text',
        'Ext.grid.property.Grid',
        'Ext.grid.RowNumberer',
        'Ext.grid.column.Number',
        'Ext.grid.View'
    ],

    id: 'use_MonitorResult',
    layout: 'fit',
    title: '监测抽样结果',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    layout: 'border',
                    items: [
                        {
                            xtype: 'panel',
                            region: 'east',
                            split: true,
                            width: 180,
                            layout: 'border',
                            items: [
                                {
                                    xtype: 'panel',
                                    region: 'center',
                                    title: '抽样结果',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            margin: 5,
                                            fieldLabel: '样本点总数',
                                            value: 231,
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            margin: 5,
                                            fieldLabel: '抽样精度',
                                            value: '83.3%',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            margin: 5,
                                            fieldLabel: '实际总费用(元)',
                                            value: 11240,
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'propertygrid',
                                            title: '知识层统计结果',
                                            nameColumnWidth: 100,
                                            source: {
                                                ' 极度敏感区': 2,
                                                ' 高度敏感区': 158,
                                                ' 中度敏感区': 41,
                                                ' 低度敏感区': 23,
                                                ' 不敏感区': 7
                                            },
                                            listeners: {
                                                afterrender: {
                                                    fn: me.onPropertygridAfterRender,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'propertygrid',
                                            title: '报告层统计结果',
                                            nameColumnWidth: 100,
                                            source: {
                                                ' 双龙镇长寿寨': 5,
                                                ' 双龙镇飞石村': 16,
                                                ' 双龙镇谷黄村': 23,
                                                ' 双龙镇红岩村': 20,
                                                ' 双龙镇尖山村': 28,
                                                ' 双龙镇建制镇': 11,
                                                ' 双龙镇龙滩村': 16,
                                                ' 双龙镇罗围村': 38,
                                                ' 双龙镇群力村': 25,
                                                ' 双龙镇天堂村': 3,
                                                ' 双龙镇连丰村': 15,
                                                ' 双龙镇联合村': 31
                                            },
                                            listeners: {
                                                afterrender: {
                                                    fn: me.onPropertygridAfterRender1,
                                                    scope: me
                                                }
                                            }
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            region: 'center',
                            split: true,
                            layout: 'border',
                            items: [
                                {
                                    xtype: 'panel',
                                    region: 'south',
                                    split: true,
                                    height: 200,
                                    layout: 'fit',
                                    title: '抽样点属性表',
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            id: 'grid_useMonitorResult_SamplesAttr',
                                            columns: [
                                                {
                                                    xtype: 'rownumberer'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    width: 150,
                                                    dataIndex: 'qsdwmc',
                                                    text: '权属单位名称'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'tbbh',
                                                    text: '图斑编号',
                                                    format: '0'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'dlmc',
                                                    text: '地类名称'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'dlbm',
                                                    text: '地类编码',
                                                    format: '0'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    width: 80,
                                                    dataIndex: 'bsm',
                                                    text: '标识码',
                                                    format: '0'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    width: 120,
                                                    dataIndex: 'ysdm',
                                                    text: '要素代码',
                                                    format: '0'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    region: 'center',
                                    html: '<div id = "mapdiv_MonitorResult" style = "width=100%;height:100%;">\r\n</div>',
                                    layout: 'fit',
                                    title: '抽样点空间分布',
                                    listeners: {
                                        afterrender: {
                                            fn: me.onPanelAfterRender,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onPropertygridAfterRender: function(component, eOpts) {
        component.getView().getHeaderCt().getHeaderAtIndex(0).setText('知识层');
        component.getView().getHeaderCt().getHeaderAtIndex(1).setText('样本点个数');
    },

    onPropertygridAfterRender1: function(component, eOpts) {
        component.getView().getHeaderCt().getHeaderAtIndex(0).setText('报告层');
        component.getView().getHeaderCt().getHeaderAtIndex(1).setText('样本点个数');
    },

    onPanelAfterRender: function(component, eOpts) {
        //加入地图的js文件
        var head = document.getElementsByTagName('head')[0];
        var script= document.createElement("script");
        script.type = "text/javascript";
        script.src="map/use_MonitorResult_map.js";
        head.appendChild(script);
    }

});